# port/platform/build_commit.cmake: writes OUT (ico_build_commit.h) with the
# source tree's commit, "git describe --always --dirty", as ICO_BUILD_COMMIT
# (the pad recording's header names the build). Run at every
# build (port/platform/CMakeLists.txt); the file is rewritten only when the
# value changes, so nothing recompiles otherwise.
set(_commit "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" describe --always --dirty --abbrev=10
                    OUTPUT_VARIABLE _out RESULT_VARIABLE _rc ERROR_QUIET
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(_rc EQUAL 0 AND NOT _out STREQUAL "")
        set(_commit "${_out}")
    endif()
endif()
set(_text "/* generated by port/platform/build_commit.cmake */\n#define ICO_BUILD_COMMIT \"${_commit}\"\n")
set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _text)
    file(WRITE "${OUT}" "${_text}")
endif()
