#!/usr/bin/env bash
# Regenerates rhi_test_spv.h (SPIR-V) and rhi_test_dxil.h (signed DXIL) from
# rhi_test.hlsl with DXC (the pinned release the shader toolchain uses;
# DXC=/path/to/dxc to pick one). The headers are committed so the RHI tests
# build without DXC.
#
# The -fvk-*-shift flags are the register-to-binding mapping the Vulkan
# backend expects (port/rhi/vk/README.md, "Descriptor scheme"). DXIL is
# signed by the libdxil.so beside dxc (docs/port/SHADERS.md, "DXIL
# signing"); the [[vk::...]] attributes are ignored there, hence
# -Wno-ignored-attributes.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../../.." && pwd)"
DXC="${DXC:-$ROOT/tools/toolchain/deps/dxc/bin/dxc}"
FLAGS=(-spirv -fspv-target-env=vulkan1.2 -fvk-b-shift 0 all -fvk-t-shift 16 all
       -fvk-s-shift 32 all -fvk-u-shift 48 all -O3)
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
for e in vs_main:vs_6_0 ps_dual:ps_6_0 ps_color:ps_6_0 ps_tex:ps_6_0 ps_uint:ps_6_0; do
    "$DXC" "${FLAGS[@]}" -T "${e#*:}" -E "${e%%:*}" "$HERE/rhi_test.hlsl" -Fo "$TMP/${e%%:*}.spv"
    "$DXC" -O3 -Wno-ignored-attributes -T "${e#*:}" -E "${e%%:*}" "$HERE/rhi_test.hlsl" \
        -Fo "$TMP/${e%%:*}.dxil"
done
python3 - "$TMP" "$HERE/rhi_test_spv.h" "$("$DXC" --version 2>&1 | head -n 1)" <<'PY'
import struct, sys
tmp, out, ver = sys.argv[1], sys.argv[2], sys.argv[3]
names = ["vs_main", "ps_dual", "ps_color", "ps_tex", "ps_uint"]
lines = ["/* rhi_test_spv.h: generated by gen_shaders.sh from rhi_test.hlsl; do not edit.",
         " * " + ver.strip() + " */",
         "#ifndef PORT_RHI_TEST_RHI_TEST_SPV_H", "#define PORT_RHI_TEST_RHI_TEST_SPV_H", "",
         "#include <stdint.h>", ""]
for n in names:
    data = open(f"{tmp}/{n}.spv", "rb").read()
    words = struct.unpack(f"<{len(data)//4}I", data)
    lines.append(f"static const uint32_t spv_{n}[{len(words)}] = {{")
    for i in range(0, len(words), 6):
        lines.append("    " + ", ".join(f"0x{w:08x}u" for w in words[i:i+6]) + ",")
    lines.append("};")
    lines.append("")
lines.append("#endif")
open(out, "w").write("\n".join(lines) + "\n")
PY
python3 - "$TMP" "$HERE/rhi_test_dxil.h" "$("$DXC" --version 2>&1 | head -n 1)" <<'PY'
import sys
tmp, out, ver = sys.argv[1], sys.argv[2], sys.argv[3]
names = ["vs_main", "ps_dual", "ps_color", "ps_tex", "ps_uint"]
lines = ["/* rhi_test_dxil.h: generated by gen_shaders.sh from rhi_test.hlsl; do not edit.",
         " * Signed DXIL (DXBC containers). " + ver.strip() + " */",
         "#ifndef PORT_RHI_TEST_RHI_TEST_DXIL_H", "#define PORT_RHI_TEST_RHI_TEST_DXIL_H", "",
         "#include <stdint.h>", ""]
for n in names:
    data = open(f"{tmp}/{n}.dxil", "rb").read()
    if data[:4] != b"DXBC" or data[4:20] == bytes(16):
        sys.exit(f"gen_shaders: {n}: unsigned or not a DXBC container")
    lines.append(f"static const uint8_t dxil_{n}[{len(data)}] = {{")
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i+12]) + ",")
    lines.append("};")
    lines.append("")
lines.append("#endif")
open(out, "w").write("\n".join(lines) + "\n")
PY
echo "wrote $HERE/rhi_test_spv.h and $HERE/rhi_test_dxil.h"
