/* port/test/layout_asserts.c: GENERATED by tools/gen_layout_asserts.py from
 * the ico2/ headers' offset comments and config/struct_classes.txt. Do not
 * edit; rerun the script (docs/port/LAYOUT.md).
 *
 * On the host (x64) only the frozen structs (overlay: read from disc or ELF
 * bytes; save: serialised into the save image) are asserted, except the ones
 * still pending a conversion (ICO_LAYOUT_PENDING compiles those too). The
 * runtime structs' asserts are documentation of the EE layout: they hold on a
 * build with the EE's ILP32 layout and compile only with -DICO_LAYOUT_EE=1.
 * The 32-bit host build that checked them every build was retired at Phase 2
 * exit (commit 36a1d73e). */

#include <stddef.h>

#include "typedef.h"
#include "charFileManager.h"
#include "kanban.h"
#include "layout_texture.h"
#include "sceneManager.h"
#include "act-game.h"
#include "act-parallel-control.h"
#include "act.h"
#include "adpcm_init.h"
#include "cdvd.h"
#include "commonact.h"
#include "enemy_act.h"
#include "fieldCollision.h"
#include "girl_act.h"
#include "gobj_process.h"
#include "jimaku.h"
#include "mcard.h"
#include "memory.h"
#include "message.h"
#include "pad.h"
#include "s_init.h"
#include "shockdriver.h"
#include "thread.h"
#include "way_llf.h"
#include "way_tool.h"
#include "way_util.h"
#include "act_bird.h"
#include "itou_common.h"
#include "lightning.h"
#include "mv_audiodec.h"
#include "mv_disp.h"
#include "mv_readbuf.h"
#include "mv_vibuf.h"
#include "mv_videodec.h"
#include "mv_vobuf.h"
#include "attackhit.h"
#include "camera-editor.h"
#include "ebrain.h"
#include "objact.h"
#include "e3.h"
#include "script.h"
#include "BgAnimation.h"
#include "DisplayP2O.h"
#include "Light.h"
#include "Packet.h"
#include "Primitive.h"
#include "StageAnimation.h"
#include "Tim2.h"
#include "attackCheckBoundary.h"
#include "box.h"
#include "boy.h"
#include "clipCollisionManager.h"
#include "clothAnimation.h"
#include "enemy.h"
#include "enemyParts.h"
#include "frameDependSequence.h"
#include "handManager.h"
#include "item.h"
#include "motionFileManager.h"
#include "motionOrientManager.h"
#include "multiBgaManager.h"
#include "particleEffect.h"
#include "pool.h"
#include "spider.h"
#include "stormTest.h"
#include "streamMotionManager.h"
#include "switch.h"
#include "waterDot.h"
#include "weapon.h"
#include "backStage.h"

#ifndef ICO_LAYOUT_EE
#define ICO_LAYOUT_EE 0
#endif
#ifndef ICO_LAYOUT_PENDING
#define ICO_LAYOUT_PENDING 0
#endif

#define OFF(T, m, o) _Static_assert(offsetof(T, m) == (o), #T "." #m " at " #o)
#define SIZE(T, n) _Static_assert(sizeof(T) == (n), "sizeof(" #T ") == " #n)

/* TexRec: overlay, ico2/common/include/charFileManager.h:31 */
OFF(TexRec, path, 0x0);
OFF(TexRec, cameraMove, 0x30);
SIZE(TexRec, 0x34); /* comment */

/* PObjMdl: overlay, ico2/common/include/charFileManager.h:39 */
OFF(PObjMdl, path, 0x0);
OFF(PObjMdl, collPath, 0x30);
OFF(PObjMdl, offset, 0x70);
OFF(PObjMdl, lightScale, 0x7C);
OFF(PObjMdl, ambientScale, 0x80);
OFF(PObjMdl, shadowLength, 0x84);
SIZE(PObjMdl, 0x8C); /* comment */

/* Kanban: runtime, ico2/common/include/kanban.h:19 */
#if ICO_LAYOUT_EE
OFF(Kanban, layout, 0x0);
OFF(Kanban, pri, 0x4);
OFF(Kanban, key, 0x8);
OFF(Kanban, flags, 0xC);
OFF(Kanban, alpha, 0x10);
OFF(Kanban, col, 0x14);
OFF(Kanban, next, 0x18);
OFF(Kanban, prev, 0x1C);
#endif

/* LtProperty: overlay, ico2/common/include/layout_texture.h:42, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(LtProperty, word0, 0x0);
OFF(LtProperty, word4, 0x4);
OFF(LtProperty, word8, 0x8);
OFF(LtProperty, wordC, 0xC);
OFF(LtProperty, ownerItem, 0x10);
OFF(LtProperty, word14, 0x14);
OFF(LtProperty, texData, 0x18);
OFF(LtProperty, texNo, 0x1C);
OFF(LtProperty, up, 0x20);
OFF(LtProperty, down, 0x24);
OFF(LtProperty, left, 0x28);
OFF(LtProperty, right, 0x2C);
OFF(LtProperty, rightItem, 0x30);
OFF(LtProperty, leftItem, 0x34);
OFF(LtProperty, downItem, 0x38);
OFF(LtProperty, upItem, 0x3C);
OFF(LtProperty, word40, 0x40);
OFF(LtProperty, centerX, 0x44);
OFF(LtProperty, dispH, 0x48);
OFF(LtProperty, dispW, 0x4C);
OFF(LtProperty, dispY, 0x50);
OFF(LtProperty, dispX, 0x54);
OFF(LtProperty, texFileNo, 0x58);
OFF(LtProperty, texU, 0x5C);
OFF(LtProperty, texH, 0x60);
OFF(LtProperty, texW, 0x64);
OFF(LtProperty, texV, 0x68);
SIZE(LtProperty, 0x70); /* comment */
#endif

/* LtProp: overlay, ico2/common/include/layout_texture.h:87, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(LtProp, first, 0x0);
OFF(LtProp, last, 0x4);
OFF(LtProp, fadeInTime, 0x8);
OFF(LtProp, fadeOutTime, 0xC);
OFF(LtProp, colR, 0x10);
OFF(LtProp, colG, 0x14);
OFF(LtProp, colB, 0x18);
OFF(LtProp, colA, 0x1C);
OFF(LtProp, proc, 0x20);
OFF(LtProp, procFirst, 0x24);
OFF(LtProp, defaultItem, 0x28);
OFF(LtProp, curItem, 0x2C);
OFF(LtProp, link, 0x30);
OFF(LtProp, word34, 0x34);
SIZE(LtProp, 0x38); /* comment */
#endif

/* SObjSimpleSetting: runtime, ico2/common/include/sceneManager.h:22 */
#if ICO_LAYOUT_EE
OFF(SObjSimpleSetting, pos, 0x0);
OFF(SObjSimpleSetting, rot, 0x10);
OFF(SObjSimpleSetting, scale, 0x20);
OFF(SObjSimpleSetting, obj, 0x30);
SIZE(SObjSimpleSetting, 0x40); /* comment */
#endif

/* EnemyMdlRec: overlay, ico2/common/include/sceneManager.h:45 */
OFF(EnemyMdlRec, name, 0x0);
OFF(EnemyMdlRec, first, 0x20);
OFF(EnemyMdlRec, last, 0x24);
SIZE(EnemyMdlRec, 0x28); /* comment */

/* struct DObjNode: runtime, ico2/common/include/typedef.h:197 */
#if ICO_LAYOUT_EE
OFF(struct DObjNode, rot, 0x0);
OFF(struct DObjNode, word10, 0x10);
OFF(struct DObjNode, scale, 0x20);
OFF(struct DObjNode, fade, 0x30);
OFF(struct DObjNode, alpha, 0x34);
OFF(struct DObjNode, flags, 0x38);
OFF(struct DObjNode, pos, 0x40);
SIZE(struct DObjNode, 0x50); /* comment */
#endif

/* struct GObj: runtime, ico2/common/include/typedef.h:232 */
#if ICO_LAYOUT_EE
OFF(struct GObj, self, 0x0);
OFF(struct GObj, labelType, 0x4);
OFF(struct GObj, labelId, 0x8);
OFF(struct GObj, kind, 0xC);
OFF(struct GObj, next, 0x10);
OFF(struct GObj, prev, 0x14);
OFF(struct GObj, linkId, 0x18);
OFF(struct GObj, pad19, 0x19);
OFF(struct GObj, key, 0x1C);
OFF(struct GObj, pad20, 0x20);
OFF(struct GObj, word24, 0x24);
OFF(struct GObj, fn, 0x28);
OFF(struct GObj, procHead, 0x2C);
OFF(struct GObj, procTail, 0x30);
OFF(struct GObj, dlNext, 0x34);
OFF(struct GObj, dlPrev, 0x38);
OFF(struct GObj, kindNext, 0x3C);
OFF(struct GObj, dlLinkId, 0x40);
OFF(struct GObj, pad41, 0x41);
OFF(struct GObj, dlKey, 0x44);
OFF(struct GObj, dl, 0x48);
OFF(struct GObj, kindMask, 0x4C);
OFF(struct GObj, drawMask, 0x50);
OFF(struct GObj, mailBox, 0x54);
OFF(struct GObj, dobj, 0x15C);
OFF(struct GObj, pad160, 0x160);
OFF(struct GObj, act, 0x164);
OFF(struct GObj, pad168, 0x168);
OFF(struct GObj, active, 0x16C);
OFF(struct GObj, pauseExempt, 0x170);
#endif

/* MotOriReq: runtime, ico2/common/include/typedef.h:306 */
#if ICO_LAYOUT_EE
OFF(MotOriReq, a, 0x0);
OFF(MotOriReq, aw, 0xC);
OFF(MotOriReq, b, 0x10);
OFF(MotOriReq, bw, 0x1C);
SIZE(MotOriReq, 0x20); /* comment */
#endif

/* HandRec: runtime, ico2/common/include/typedef.h:324 */
#if ICO_LAYOUT_EE
OFF(HandRec, mode, 0x0);
OFF(HandRec, obj, 0x4);
OFF(HandRec, node, 0x8);
OFF(HandRec, pad0C, 0xC);
OFF(HandRec, pos, 0x10);
OFF(HandRec, ikMode, 0x20);
OFF(HandRec, ikLock, 0x24);
OFF(HandRec, pad28, 0x28);
OFF(HandRec, ikDir, 0x30);
OFF(HandRec, ikQuat, 0x40);
OFF(HandRec, ikRate, 0x50);
OFF(HandRec, ikReached, 0x54);
OFF(HandRec, ikFlag, 0x58);
OFF(HandRec, pad5C, 0x5C);
SIZE(HandRec, 0x60); /* comment */
#endif

/* struct MotRoot: runtime, ico2/common/include/typedef.h:348 */
#if ICO_LAYOUT_EE
OFF(struct MotRoot, pos, 0x0);
OFF(struct MotRoot, trans, 0x10);
OFF(struct MotRoot, baseQuat, 0x20);
OFF(struct MotRoot, quat, 0x30);
OFF(struct MotRoot, motionQuat, 0x40);
OFF(struct MotRoot, twist, 0x50);
OFF(struct MotRoot, _pad52, 0x52);
OFF(struct MotRoot, twistRate, 0x54);
OFF(struct MotRoot, _pad58, 0x58);
OFF(struct MotRoot, up, 0x60);
OFF(struct MotRoot, savePos, 0x70);
OFF(struct MotRoot, hitObj, 0x80);
OFF(struct MotRoot, _pad88, 0x88);
OFF(struct MotRoot, move, 0x90);
OFF(struct MotRoot, step, 0xA0);
OFF(struct MotRoot, itemQuat, 0xB0);
OFF(struct MotRoot, height, 0xC0);
OFF(struct MotRoot, _padC4, 0xC4);
OFF(struct MotRoot, delta, 0xD0);
OFF(struct MotRoot, wall, 0xE0);
OFF(struct MotRoot, wallCount, 0xEC);
OFF(struct MotRoot, cliffWall, 0xF0);
OFF(struct MotRoot, cliffWallCount, 0xFC);
OFF(struct MotRoot, aheadWall, 0x100);
OFF(struct MotRoot, _pad10C, 0x10C);
OFF(struct MotRoot, filter, 0x120);
OFF(struct MotRoot, _pad12C, 0x12C);
OFF(struct MotRoot, plane, 0x130);
OFF(struct MotRoot, lastField, 0x140);
OFF(struct MotRoot, cliffFloor, 0x144);
OFF(struct MotRoot, _pad148, 0x148);
OFF(struct MotRoot, last, 0x150);
OFF(struct MotRoot, clipFrom, 0x160);
OFF(struct MotRoot, stepMove, 0x170);
OFF(struct MotRoot, standNode, 0x180);
OFF(struct MotRoot, _pad184, 0x184);
OFF(struct MotRoot, focusPos, 0x190);
OFF(struct MotRoot, focusLocal, 0x1A0);
OFF(struct MotRoot, footPos, 0x1B0);
OFF(struct MotRoot, reservePos, 0x1C0);
OFF(struct MotRoot, projHeight, 0x1D0);
OFF(struct MotRoot, _pad1D4, 0x1D4);
OFF(struct MotRoot, liftOn, 0x200);
OFF(struct MotRoot, lifting, 0x204);
OFF(struct MotRoot, lift, 0x208);
OFF(struct MotRoot, hand1, 0x210);
OFF(struct MotRoot, hand0, 0x270);
OFF(struct MotRoot, armTwist, 0x2D0);
OFF(struct MotRoot, lookMode, 0x2E0);
OFF(struct MotRoot, _pad2E4, 0x2E4);
OFF(struct MotRoot, lookPos, 0x2F0);
OFF(struct MotRoot, h, 0x300);
OFF(struct MotRoot, p, 0x302);
OFF(struct MotRoot, b, 0x304);
OFF(struct MotRoot, _pad306, 0x306);
OFF(struct MotRoot, noStepSearch, 0x308);
OFF(struct MotRoot, gravity, 0x30C);
OFF(struct MotRoot, slopeIK, 0x310);
OFF(struct MotRoot, stairStep, 0x314);
OFF(struct MotRoot, lookIK, 0x318);
OFF(struct MotRoot, handTurnIK, 0x31C);
OFF(struct MotRoot, fieldWall, 0x320);
OFF(struct MotRoot, fuchiMode, 0x324);
OFF(struct MotRoot, cylinder, 0x328);
OFF(struct MotRoot, avgWallPlane, 0x32C);
OFF(struct MotRoot, flag330, 0x330);
OFF(struct MotRoot, flag334, 0x334);
OFF(struct MotRoot, radius, 0x338);
OFF(struct MotRoot, radiusTo, 0x33C);
OFF(struct MotRoot, radiusFrom, 0x340);
OFF(struct MotRoot, _pad344, 0x344);
OFF(struct MotRoot, cliffPlane, 0x350);
OFF(struct MotRoot, handIK, 0x360);
OFF(struct MotRoot, stepNode, 0x364);
OFF(struct MotRoot, _pad368, 0x368);
OFF(struct MotRoot, holdPoint, 0x370);
OFF(struct MotRoot, ropeState, 0x380);
OFF(struct MotRoot, fixObj, 0x384);
OFF(struct MotRoot, fixNode, 0x388);
OFF(struct MotRoot, _pad38C, 0x38C);
OFF(struct MotRoot, fixQuat, 0x390);
OFF(struct MotRoot, fixPos, 0x3A0);
OFF(struct MotRoot, fixWeight, 0x3B0);
OFF(struct MotRoot, fixMode, 0x3B4);
OFF(struct MotRoot, footIKRate, 0x3B8);
OFF(struct MotRoot, ikRate0, 0x3BC);
OFF(struct MotRoot, handRate, 0x3C0);
OFF(struct MotRoot, ikRate1, 0x3C4);
OFF(struct MotRoot, ikRate2, 0x3C8);
OFF(struct MotRoot, _pad3CC, 0x3CC);
#endif

/* struct MotCtrl: runtime, ico2/common/include/typedef.h:458 */
#if ICO_LAYOUT_EE
OFF(struct MotCtrl, stream, 0x0);
OFF(struct MotCtrl, oriFrom, 0x4);
OFF(struct MotCtrl, oriTo, 0x8);
OFF(struct MotCtrl, shifted, 0xC);
OFF(struct MotCtrl, ctrlFlags, 0x10);
OFF(struct MotCtrl, flags, 0x14);
OFF(struct MotCtrl, shiftStop, 0x18);
OFF(struct MotCtrl, shiftReq, 0x1C);
OFF(struct MotCtrl, shiftNext, 0x20);
OFF(struct MotCtrl, shiftFrom, 0x24);
OFF(struct MotCtrl, shiftMode, 0x28);
OFF(struct MotCtrl, request, 0x2C);
OFF(struct MotCtrl, motion, 0x30);
OFF(struct MotCtrl, noAlt, 0x34);
OFF(struct MotCtrl, shiftReady, 0x38);
OFF(struct MotCtrl, animFrame, 0x3C);
OFF(struct MotCtrl, lastFrame, 0x40);
OFF(struct MotCtrl, playTime, 0x44);
OFF(struct MotCtrl, speedRatio, 0x48);
OFF(struct MotCtrl, playRate, 0x4C);
OFF(struct MotCtrl, frameRatio, 0x50);
OFF(struct MotCtrl, waterDrag, 0x54);
OFF(struct MotCtrl, justShifted, 0x58);
OFF(struct MotCtrl, frameEnd, 0x5C);
OFF(struct MotCtrl, keepUpdateMode, 0x60);
OFF(struct MotCtrl, updateModeChanged, 0x64);
OFF(struct MotCtrl, rootUpdateMode, 0x68);
OFF(struct MotCtrl, parallelEnded, 0x6C);
OFF(struct MotCtrl, parallel, 0x70);
OFF(struct MotCtrl, orientUpdateOff, 0x74);
OFF(struct MotCtrl, noStand, 0x78);
OFF(struct MotCtrl, posReserve, 0x7C);
OFF(struct MotCtrl, loopFlag, 0x80);
OFF(struct MotCtrl, reserveBlend, 0x84);
OFF(struct MotCtrl, reserveMoved, 0x88);
OFF(struct MotCtrl, step, 0x8C);
OFF(struct MotCtrl, orientReq, 0x90);
OFF(struct MotCtrl, lastMotion, 0x94);
OFF(struct MotCtrl, lastNoAlt, 0x98);
OFF(struct MotCtrl, shiftFrame, 0x9C);
OFF(struct MotCtrl, blendCount, 0xA0);
OFF(struct MotCtrl, blendFrames, 0xA4);
OFF(struct MotCtrl, _padA8, 0xA8);
OFF(struct MotCtrl, dir, 0xB0);
OFF(struct MotCtrl, lastDir, 0xC0);
OFF(struct MotCtrl, orientKind, 0xD0);
OFF(struct MotCtrl, floorFit, 0xD4);
OFF(struct MotCtrl, wallReact, 0xD8);
OFF(struct MotCtrl, cliffWallCheck, 0xDC);
OFF(struct MotCtrl, catchBoy, 0xE0);
OFF(struct MotCtrl, sideWallCheck, 0xE4);
OFF(struct MotCtrl, variation, 0xE8);
OFF(struct MotCtrl, fallHeight, 0xEC);
OFF(struct MotCtrl, groundHeight, 0xF0);
OFF(struct MotCtrl, wallHit, 0xF4);
OFF(struct MotCtrl, cliffEdge, 0xF8);
OFF(struct MotCtrl, cliffWallHit, 0xFC);
OFF(struct MotCtrl, cliffBack, 0x100);
OFF(struct MotCtrl, fieldWallHit, 0x104);
OFF(struct MotCtrl, upperWall, 0x108);
OFF(struct MotCtrl, sideWall, 0x10C);
OFF(struct MotCtrl, cliffHeight, 0x110);
OFF(struct MotCtrl, cliffDist, 0x114);
OFF(struct MotCtrl, _pad118, 0x118);
OFF(struct MotCtrl, cliffNormal, 0x120);
OFF(struct MotCtrl, wallFloorHeight, 0x130);
OFF(struct MotCtrl, wallTopHeight, 0x134);
OFF(struct MotCtrl, wallDist, 0x138);
OFF(struct MotCtrl, _pad13C, 0x13C);
OFF(struct MotCtrl, wallDir, 0x140);
OFF(struct MotCtrl, wallNormal, 0x150);
OFF(struct MotCtrl, sideWallNormal, 0x160);
OFF(struct MotCtrl, upperWallDist, 0x170);
OFF(struct MotCtrl, sideWallDist, 0x174);
OFF(struct MotCtrl, cliffDepth, 0x178);
OFF(struct MotCtrl, pureWallAttr, 0x17C);
OFF(struct MotCtrl, pureCliffAttr, 0x180);
OFF(struct MotCtrl, wallAttr, 0x184);
OFF(struct MotCtrl, floorAttr, 0x188);
OFF(struct MotCtrl, _pad18C, 0x18C);
OFF(struct MotCtrl, frameFlag1, 0x190);
OFF(struct MotCtrl, frameFlag2, 0x194);
OFF(struct MotCtrl, trigger1, 0x198);
OFF(struct MotCtrl, trigger1Done, 0x19C);
OFF(struct MotCtrl, trigger2, 0x1A0);
OFF(struct MotCtrl, trigger2Done, 0x1A4);
OFF(struct MotCtrl, ropeHangPos, 0x1A8);
OFF(struct MotCtrl, seGroup, 0x1AC);
OFF(struct MotCtrl, slipFlags, 0x1B4);
OFF(struct MotCtrl, lastSlipFlags, 0x1B8);
OFF(struct MotCtrl, slipOn, 0x1BC);
OFF(struct MotCtrl, pickedWeapon, 0x1C0);
OFF(struct MotCtrl, keepWall, 0x1C4);
OFF(struct MotCtrl, keepStand, 0x1C8);
OFF(struct MotCtrl, landed, 0x1CC);
OFF(struct MotCtrl, waterY, 0x1D0);
OFF(struct MotCtrl, waterDepth, 0x1D4);
OFF(struct MotCtrl, pool, 0x1D8);
OFF(struct MotCtrl, contactFlags, 0x1DC);
OFF(struct MotCtrl, mailDelay, 0x1E0);
OFF(struct MotCtrl, noFieldClip, 0x1E4);
OFF(struct MotCtrl, seMute, 0x1E8);
OFF(struct MotCtrl, _pad1EC, 0x1EC);
#endif

/* SkelNode: overlay, ico2/common/include/typedef.h:573 */
OFF(SkelNode, mirror, 0x0);
OFF(SkelNode, kind, 0x4);
OFF(SkelNode, pad08, 0x8);
OFF(SkelNode, pos, 0x10);
OFF(SkelNode, quat, 0x20);
OFF(SkelNode, child, 0x30);
OFF(SkelNode, sibling, 0x34);
OFF(SkelNode, parent, 0x38);
OFF(SkelNode, pad3C, 0x3C);
SIZE(SkelNode, 0x40); /* comment */

/* MotIk: runtime, ico2/common/include/typedef.h:591 */
#if ICO_LAYOUT_EE
OFF(MotIk, rate, 0x0);
OFF(MotIk, prevH, 0x4);
OFF(MotIk, pad06, 0x6);
OFF(MotIk, pitch, 0x8);
OFF(MotIk, pad0A, 0xA);
OFF(MotIk, pitchSpeed, 0xE);
OFF(MotIk, q, 0x10);
OFF(MotIk, step, 0x20);
OFF(MotIk, offset, 0x30);
SIZE(MotIk, 0x40); /* comment */
#endif

/* struct Sub15C: runtime, ico2/common/include/typedef.h:609 */
#if ICO_LAYOUT_EE
OFF(struct Sub15C, parent, 0x0);
OFF(struct Sub15C, nodeNum, 0x8);
OFF(struct Sub15C, nodeMtx, 0xC);
OFF(struct Sub15C, nodeQuat, 0x10);
OFF(struct Sub15C, pad14, 0x14);
OFF(struct Sub15C, matrix, 0x20);
OFF(struct Sub15C, quat, 0x60);
OFF(struct Sub15C, colData, 0x70);
OFF(struct Sub15C, disp, 0x74);
OFF(struct Sub15C, colRotate, 0x78);
OFF(struct Sub15C, cylinderOn, 0x7C);
OFF(struct Sub15C, colPerNode, 0x80);
OFF(struct Sub15C, modelId, 0x84);
OFF(struct Sub15C, skelNodeNum, 0x88);
OFF(struct Sub15C, skel, 0x8C);
OFF(struct Sub15C, clusterMtx, 0x90);
OFF(struct Sub15C, pad94, 0x94);
OFF(struct Sub15C, root, 0xA0);
OFF(struct Sub15C, ctrl, 0x470);
OFF(struct Sub15C, streamScale, 0x660);
OFF(struct Sub15C, pad664, 0x664);
OFF(struct Sub15C, streamOfs, 0x670);
OFF(struct Sub15C, pad67C, 0x67C);
OFF(struct Sub15C, motion, 0x680);
OFF(struct Sub15C, fdsFlags, 0x740);
OFF(struct Sub15C, motionBuf, 0x7B4);
OFF(struct Sub15C, pad7B8, 0x7B8);
OFF(struct Sub15C, motionPos, 0x7C0);
OFF(struct Sub15C, blendBuf, 0x7D0);
OFF(struct Sub15C, pad7D4, 0x7D4);
OFF(struct Sub15C, localPos, 0x7E0);
OFF(struct Sub15C, localMove, 0x7F0);
OFF(struct Sub15C, local, 0x800);
OFF(struct Sub15C, localHeight, 0x808);
OFF(struct Sub15C, nodeRotElem, 0x80C);
OFF(struct Sub15C, nodeLimit, 0x810);
OFF(struct Sub15C, nodeVec, 0x814);
OFF(struct Sub15C, blendRot, 0x818);
OFF(struct Sub15C, rideFunc, 0x81C);
OFF(struct Sub15C, blendless, 0x820);
OFF(struct Sub15C, scaleRatio, 0x824);
OFF(struct Sub15C, pad828, 0x828);
OFF(struct Sub15C, work, 0x830);
OFF(struct Sub15C, morphNum, 0x834);
OFF(struct Sub15C, morphWeight, 0x838);
OFF(struct Sub15C, lightId, 0x83C);
OFF(struct Sub15C, focusNodes, 0x840);
OFF(struct Sub15C, accessary, 0x844);
OFF(struct Sub15C, lodFunc, 0x848);
OFF(struct Sub15C, dispType, 0x84C);
OFF(struct Sub15C, pad84E, 0x84E);
OFF(struct Sub15C, lineHdr, 0x850);
OFF(struct Sub15C, model, 0x854);
OFF(struct Sub15C, shadow, 0x858);
OFF(struct Sub15C, pad85C, 0x85C);
OFF(struct Sub15C, shadowDir, 0x860);
OFF(struct Sub15C, nodes, 0x870);
OFF(struct Sub15C, lightMtx, 0x874);
#endif

/* StageSetting: overlay, ico2/common/include/typedef.h:905 */
OFF(StageSetting, flatLightDir, 0x0);
OFF(StageSetting, flatLightCol, 0x30);
OFF(StageSetting, ambientCol, 0x60);
OFF(StageSetting, bgCol, 0x70);
OFF(StageSetting, fogOn, 0x80);
OFF(StageSetting, pad084, 0x84);
OFF(StageSetting, fogColR, 0x90);
OFF(StageSetting, fogColG, 0x94);
OFF(StageSetting, fogColB, 0x98);
OFF(StageSetting, fogColA, 0x9C);
OFF(StageSetting, fogOffsetA, 0xA0);
OFF(StageSetting, fogNear, 0xA4);
OFF(StageSetting, fogFar, 0xA8);
OFF(StageSetting, shadowDepth, 0xAC);
OFF(StageSetting, shadowBlend, 0xB0);
OFF(StageSetting, shadowColR, 0xC0);
OFF(StageSetting, shadowColG, 0xC4);
OFF(StageSetting, shadowColB, 0xC8);
OFF(StageSetting, pad0CC, 0xCC);
OFF(StageSetting, reductionCol, 0xD0);
OFF(StageSetting, pad0DC, 0xDC);
OFF(StageSetting, viewScale, 0xE0);
OFF(StageSetting, texSampleMode, 0xE4);
OFF(StageSetting, postEffect, 0xE8);
OFF(StageSetting, depthFieldStart, 0xEC);
OFF(StageSetting, depthFieldWidth, 0xF0);
OFF(StageSetting, motionBlur, 0xF4);
OFF(StageSetting, depthFieldLevel, 0xF8);
OFF(StageSetting, antiLevel0, 0xFC);
OFF(StageSetting, antiLevel1, 0x100);
OFF(StageSetting, feedbackEffect, 0x104);
OFF(StageSetting, pad108, 0x108);
OFF(StageSetting, feedbackCol, 0x110);
OFF(StageSetting, fogStrength, 0x120);
OFF(StageSetting, pad124, 0x124);
OFF(StageSetting, targetCol, 0x130);
OFF(StageSetting, grainScale, 0x170);
OFF(StageSetting, pad174, 0x174);
OFF(StageSetting, handCameraLimitP, 0x180);
OFF(StageSetting, handCameraLimitV, 0x184);
OFF(StageSetting, pad188, 0x188);
OFF(StageSetting, zoomMaxInDemo, 0x190);
OFF(StageSetting, pad194, 0x194);
OFF(StageSetting, antiLevel, 0x19C);
OFF(StageSetting, subMotionBlur, 0x1BC);
SIZE(StageSetting, 0x1D0); /* config */

/* BrainTarget: runtime, ico2/common/include/typedef.h:992 */
#if ICO_LAYOUT_EE
OFF(BrainTarget, levelCap, 0x8);
OFF(BrainTarget, capStep, 0xC);
OFF(BrainTarget, rate, 0x10);
OFF(BrainTarget, lookOnly, 0x18);
OFF(BrainTarget, alwaysSeen, 0x19);
OFF(BrainTarget, detail, 0x1A);
OFF(BrainTarget, pad1B, 0x1B);
#endif

/* GsysObjInfo: save, ico2/common/include/typedef.h:1023 */
OFF(GsysObjInfo, pad0, 0x0);
OFF(GsysObjInfo, kind, 0x20);
OFF(GsysObjInfo, pad24, 0x24);

/* McDirEnt: save, ico2/common/include/typedef.h:1035 */
OFF(McDirEnt, pad0, 0x0);
OFF(McDirEnt, size, 0x10);
OFF(McDirEnt, pad14, 0x14);
OFF(McDirEnt, name, 0x20);

/* PadState: runtime, ico2/common/include/typedef.h:1049 */
#if ICO_LAYOUT_EE
OFF(PadState, now, 0x0);
OFF(PadState, flags, 0x4);
OFF(PadState, rel, 0x8);
OFF(PadState, rep, 0xC);
OFF(PadState, old, 0x10);
OFF(PadState, hist, 0x14);
OFF(PadState, ana, 0x54);
#endif

/* ObjKindEnt: overlay, ico2/common/include/typedef.h:1068, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(ObjKindEnt, name, 0x0);
OFF(ObjKindEnt, targetTime, 0x24);
OFF(ObjKindEnt, brainCapStep, 0x28);
OFF(ObjKindEnt, brainRate, 0x2C);
OFF(ObjKindEnt, brainLevel, 0x30);
OFF(ObjKindEnt, infoLoad, 0x34);
OFF(ObjKindEnt, infoInit, 0x38);
OFF(ObjKindEnt, uniqDataSet, 0x3C);
OFF(ObjKindEnt, start, 0x40);
OFF(ObjKindEnt, layouted, 0x44);
OFF(ObjKindEnt, dl, 0x48);
OFF(ObjKindEnt, afterGeo, 0x4C);
OFF(ObjKindEnt, geo, 0x50);
OFF(ObjKindEnt, hotInit, 0x54);
OFF(ObjKindEnt, create, 0x58);
OFF(ObjKindEnt, ai, 0x5C);
OFF(ObjKindEnt, before, 0x60);
SIZE(ObjKindEnt, 0x64); /* comment */
#endif

/* StgPre: overlay, ico2/common/include/typedef.h:1094, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(StgPre, key, 0x0);
OFF(StgPre, name, 0x20);
OFF(StgPre, key2, 0x40);
OFF(StgPre, fog, 0x60);
OFF(StgPre, dataFile, 0x80);
OFF(StgPre, ent, 0xA0);
OFF(StgPre, windDir, 0xC0);
OFF(StgPre, windPos, 0xCC);
OFF(StgPre, bgCol, 0xD8);
OFF(StgPre, ambientCol, 0xE4);
OFF(StgPre, flatLightCol, 0xF0);
OFF(StgPre, flatLightDir, 0xFC);
OFF(StgPre, seSegFirst, 0x108);
OFF(StgPre, seSegLast, 0x10C);
OFF(StgPre, seEnvFirst, 0x110);
OFF(StgPre, seEnvLast, 0x114);
OFF(StgPre, camSetId, 0x118);
OFF(StgPre, word11C, 0x11C);
OFF(StgPre, animLayoutFirst, 0x120);
OFF(StgPre, animLayoutLast, 0x124);
OFF(StgPre, labelTop, 0x128);
OFF(StgPre, labelEnd, 0x12C);
OFF(StgPre, layoutFirst, 0x130);
OFF(StgPre, layoutLast, 0x134);
OFF(StgPre, mdl, 0x138);
OFF(StgPre, word148, 0x148);
OFF(StgPre, mot, 0x14C);
OFF(StgPre, endproc, 0x150);
OFF(StgPre, initproc, 0x154);
OFF(StgPre, windAmp, 0x158);
OFF(StgPre, windSpeed, 0x15C);
OFF(StgPre, word160, 0x160);
OFF(StgPre, wayGroupEnd, 0x164);
OFF(StgPre, seSegData1, 0x168);
OFF(StgPre, seSegData2, 0x16C);
OFF(StgPre, wayGroupStart, 0x170);
OFF(StgPre, word174, 0x174);
OFF(StgPre, word178, 0x178);
OFF(StgPre, word17C, 0x17C);
OFF(StgPre, ledgeRange, 0x180);
OFF(StgPre, handCameraRate, 0x184);
OFF(StgPre, shadowDepth, 0x188);
OFF(StgPre, pad18A, 0x18A);
SIZE(StgPre, 0x194); /* comment */
#endif

/* ClipWork: runtime, ico2/common/include/typedef.h:1179 */
#if ICO_LAYOUT_EE
OFF(ClipWork, pt, 0x0);
OFF(ClipWork, reflect.bounce, 0x30);
OFF(ClipWork, reflect.slide, 0x40);
OFF(ClipWork, reflect.pos, 0x50);
OFF(ClipWork, reflect.dir, 0x60);
OFF(ClipWork, radius, 0x70);
OFF(ClipWork, filter, 0x74);
OFF(ClipWork, wall, 0x80);
OFF(ClipWork, floor, 0x8C);
OFF(ClipWork, attr, 0x98);
OFF(ClipWork, pad9C, 0x9C);
OFF(ClipWork, normal, 0xA0);
OFF(ClipWork, slideCount, 0xB0);
OFF(ClipWork, padB4, 0xB4);
#endif

/* Brain: runtime, ico2/common/include/typedef.h:1200 */
#if ICO_LAYOUT_EE
OFF(Brain, lock, 0x8);
OFF(Brain, spMode, 0xC);
OFF(Brain, spCount, 0x10);
OFF(Brain, threshold, 0x14);
OFF(Brain, minThreshold, 0x18);
OFF(Brain, targetType, 0x1C);
OFF(Brain, pad1E, 0x1E);
OFF(Brain, targetLevel, 0x20);
OFF(Brain, pad26, 0x26);
#endif

/* ViTs: runtime, ico2/common/include/typedef.h:1223 */
#if ICO_LAYOUT_EE
OFF(ViTs, pts, 0x0);
OFF(ViTs, dts, 0x8);
OFF(ViTs, pos, 0x10);
OFF(ViTs, len, 0x14);
#endif

/* Pad: runtime, ico2/common/include/typedef.h:1231 */
#if ICO_LAYOUT_EE
OFF(Pad, now, 0x0);
OFF(Pad, trg, 0x4);
OFF(Pad, pad08, 0x8);
OFF(Pad, ana, 0x54);
#endif

/* ExitData: overlay, ico2/common/include/typedef.h:1239 */
OFF(ExitData, firstWalk0, 0x18);
OFF(ExitData, nextStage, 0x24);

/* ActMail: runtime, ico2/common/include/typedef.h:1253 */
#if ICO_LAYOUT_EE
OFF(ActMail, mail, 0x0);
OFF(ActMail, func, 0x4);
OFF(ActMail, motion, 0x8);
OFF(ActMail, sub, 0xC);
#endif

/* WVTObj: runtime, ico2/common/include/typedef.h:1357 */
#if ICO_LAYOUT_EE
OFF(WVTObj, pad00, 0x0);
OFF(WVTObj, pos, 0x10);
OFF(WVTObj, chk, 0x20);
OFF(WVTObj, nearWp, 0x2C);
OFF(WVTObj, stampFrame, 0x30);
OFF(WVTObj, direction, 0x34);
OFF(WVTObj, avoiding, 0x38);
OFF(WVTObj, flag3C, 0x3C);
OFF(WVTObj, pad40, 0x40);
OFF(WVTObj, reached, 0x44);
OFF(WVTObj, pad48, 0x48);
OFF(WVTObj, nrm, 0x50);
OFF(WVTObj, group, 0x60);
OFF(WVTObj, guideFirst, 0x64);
OFF(WVTObj, escapeFound, 0x68);
OFF(WVTObj, flag6C, 0x6C);
OFF(WVTObj, pathKind, 0x70);
OFF(WVTObj, fromWp, 0x74);
OFF(WVTObj, pad78, 0x78);
SIZE(WVTObj, 0x80); /* comment */
#endif

/* WayRequest: runtime, ico2/common/include/typedef.h:1386 */
#if ICO_LAYOUT_EE
OFF(WayRequest, done, 0x0);
OFF(WayRequest, result, 0x4);
OFF(WayRequest, pad08, 0x8);
OFF(WayRequest, from, 0x10);
OFF(WayRequest, way, 0x20);
OFF(WayRequest, goal, 0xA0);
OFF(WayRequest, proc, 0xB0);
#endif

/* ActEnv: runtime, ico2/common/include/typedef.h:1401 */
#if ICO_LAYOUT_EE
OFF(ActEnv, wallOrient, 0x0);
OFF(ActEnv, cliffOrient, 0x10);
OFF(ActEnv, torchOrient, 0x20);
OFF(ActEnv, torchRevOrient, 0x30);
OFF(ActEnv, cliffEdgePos, 0x40);
OFF(ActEnv, cliffStepPos, 0x50);
OFF(ActEnv, ditchPos, 0x60);
OFF(ActEnv, ditchDir, 0x70);
OFF(ActEnv, ditchCarry, 0x80);
OFF(ActEnv, pad81, 0x81);
OFF(ActEnv, cliffBackPos, 0x90);
OFF(ActEnv, edgeOrient, 0xA0);
OFF(ActEnv, sofaOrient, 0xB0);
OFF(ActEnv, edgePos, 0xC0);
OFF(ActEnv, padD0, 0xD0);
OFF(ActEnv, wallPos, 0xE0);
OFF(ActEnv, pullPos, 0xF0);
OFF(ActEnv, sofaPos, 0x100);
OFF(ActEnv, turnDir, 0x110);
OFF(ActEnv, pad120, 0x120);
OFF(ActEnv, wallWord, 0x130);
OFF(ActEnv, cliffSel, 0x134);
OFF(ActEnv, cliffHeight, 0x138);
OFF(ActEnv, wallObj, 0x13C);
OFF(ActEnv, boxObj, 0x140);
OFF(ActEnv, holdBoxObj, 0x144);
OFF(ActEnv, barObj, 0x148);
OFF(ActEnv, pullObj, 0x14C);
OFF(ActEnv, pullParent, 0x150);
OFF(ActEnv, pad154, 0x154);
OFF(ActEnv, swapWeapon, 0x158);
OFF(ActEnv, frontObj, 0x15C);
OFF(ActEnv, cageObj, 0x160);
OFF(ActEnv, bombObj, 0x164);
OFF(ActEnv, torchRevObj, 0x168);
OFF(ActEnv, sofaObj, 0x16C);
OFF(ActEnv, motOriReq, 0x170);
OFF(ActEnv, cliffContact, 0x190);
OFF(ActEnv, supportReq, 0x1B0);
SIZE(ActEnv, 0x1D0); /* comment */
#endif

/* Act: runtime, ico2/common/include/typedef.h:1457 */
#if ICO_LAYOUT_EE
OFF(Act, brainProc, 0x0);
OFF(Act, actProc, 0x4);
OFF(Act, motProc, 0x8);
OFF(Act, motProc2, 0xC);
OFF(Act, frame, 0x10);
OFF(Act, after, 0x14);
OFF(Act, flags18, 0x18);
OFF(Act, flags20, 0x20);
OFF(Act, handFreeFrame, 0x28);
OFF(Act, intrArg, 0x2C);
OFF(Act, intrData, 0x30);
OFF(Act, actMode, 0x34);
OFF(Act, pushDir, 0x38);
OFF(Act, intrMot, 0x3C);
OFF(Act, curMot, 0x40);
OFF(Act, orientMot, 0x44);
OFF(Act, actKind, 0x48);
OFF(Act, modeFrame, 0x4C);
OFF(Act, msgBlockTimer, 0x50);
OFF(Act, mother, 0x54);
OFF(Act, bits58, 0x58);
OFF(Act, pad60, 0x60);
OFF(Act, statusWait8, 0x68);
OFF(Act, statusWait5, 0x6C);
OFF(Act, statusVal17, 0x70);
OFF(Act, statusVal18, 0x74);
OFF(Act, statusTarget, 0x78);
OFF(Act, statusOther, 0x7C);
OFF(Act, gobj80, 0x80);
OFF(Act, gobj84, 0x84);
OFF(Act, statusObj, 0x88);
OFF(Act, pad8C, 0x8C);
OFF(Act, paraStatus, 0x90);
OFF(Act, lastParaStatus, 0x98);
OFF(Act, flags, 0xA0);
OFF(Act, lookTarget, 0xA8);
OFF(Act, lookPri, 0xAC);
OFF(Act, lookMode, 0xB0);
OFF(Act, padB4, 0xB4);
OFF(Act, lookPosX, 0xC0);
OFF(Act, lookPosY, 0xC4);
OFF(Act, lookPosZ, 0xC8);
OFF(Act, padCC, 0xCC);
OFF(Act, mainMail, 0xD0);
OFF(Act, mail, 0xD4);
OFF(Act, intrKind, 0xD8);
OFF(Act, attack, 0xDC);
OFF(Act, readyFlags, 0xE0);
OFF(Act, padE4, 0xE4);
OFF(Act, jump, 0xF0);
OFF(Act, pad100, 0x100);
OFF(Act, camRootX, 0x110);
OFF(Act, camRootY, 0x114);
OFF(Act, camRootZ, 0x118);
OFF(Act, pad11C, 0x11C);
OFF(Act, dir, 0x120);
OFF(Act, motReq, 0x130);
OFF(Act, soundMot, 0x134);
OFF(Act, soundFlag, 0x138);
OFF(Act, pad139, 0x139);
OFF(Act, soundWait, 0x13A);
OFF(Act, reserved, 0x13C);
OFF(Act, reservedMail, 0x140);
OFF(Act, carrier, 0x144);
OFF(Act, carried, 0x148);
OFF(Act, brainTarget, 0x14C);
OFF(Act, weapon, 0x150);
OFF(Act, curItem, 0x154);
OFF(Act, box, 0x158);
OFF(Act, barObj, 0x15C);
OFF(Act, sofa, 0x160);
OFF(Act, pad164, 0x164);
OFF(Act, restartPosX, 0x170);
OFF(Act, restartPosY, 0x174);
OFF(Act, restartPosZ, 0x178);
OFF(Act, pad17C, 0x17C);
OFF(Act, attackTurn, 0x188);
OFF(Act, pad18C, 0x18C);
OFF(Act, chain, 0x190);
OFF(Act, lastChain, 0x194);
OFF(Act, pad198, 0x198);
OFF(Act, ropeSwingX, 0x1A0);
OFF(Act, ropeSwingY, 0x1A4);
OFF(Act, ropeSwingZ, 0x1A8);
OFF(Act, pad1AC, 0x1AC);
OFF(Act, attacker, 0x1B0);
OFF(Act, pad1B4, 0x1B4);
OFF(Act, attackDir, 0x1C0);
OFF(Act, damage, 0x1D0);
OFF(Act, hitGroup, 0x1D4);
OFF(Act, downHit, 0x1D8);
OFF(Act, stoneHit, 0x1D9);
OFF(Act, hit, 0x1DA);
OFF(Act, unguardable, 0x1DB);
OFF(Act, pad1DC, 0x1DC);
OFF(Act, life, 0x1E0);
OFF(Act, maxLife, 0x1E4);
OFF(Act, padConf, 0x1E8);
OFF(Act, pad, 0x2D8);
OFF(Act, stick, 0x338);
OFF(Act, wayMode, 0x350);
OFF(Act, pad354, 0x354);
OFF(Act, way, 0x360);
OFF(Act, wayNodeX, 0x3E0);
OFF(Act, wayNodeY, 0x3E4);
OFF(Act, wayNodeZ, 0x3E8);
OFF(Act, pad3EC, 0x3EC);
OFF(Act, wayFlags, 0x3F0);
OFF(Act, wayGoalDist, 0x3F8);
OFF(Act, wayGoalHeight, 0x3FC);
OFF(Act, wayLast, 0x400);
OFF(Act, wayTarget, 0x404);
OFF(Act, pad408, 0x408);
OFF(Act, wayFromX, 0x410);
OFF(Act, wayFromY, 0x414);
OFF(Act, wayFromZ, 0x418);
OFF(Act, pad41C, 0x41C);
OFF(Act, wayDetailX, 0x420);
OFF(Act, wayDetailY, 0x424);
OFF(Act, wayDetailZ, 0x428);
OFF(Act, pad42C, 0x42C);
OFF(Act, wayDetailFlag, 0x430);
OFF(Act, wayGoalY, 0x434);
OFF(Act, wayState, 0x438);
OFF(Act, brainAim, 0x440);
OFF(Act, infoPos, 0x444);
OFF(Act, brainStatus, 0x448);
OFF(Act, pad44C, 0x44C);
OFF(Act, attackGroup, 0x450);
OFF(Act, doorFlag, 0x454);
OFF(Act, doorDist, 0x458);
OFF(Act, doorStep, 0x45C);
OFF(Act, doorMail, 0x460);
OFF(Act, doorCamWait, 0x464);
OFF(Act, doorEndWait, 0x468);
OFF(Act, doorCamera, 0x46C);
OFF(Act, pad470, 0x470);
OFF(Act, wish0, 0x478);
OFF(Act, wish1, 0x480);
OFF(Act, wish2, 0x488);
OFF(Act, wish3, 0x490);
OFF(Act, wish4, 0x498);
OFF(Act, pad4A0, 0x4A0);
OFF(Act, env, 0x4B0);
OFF(Act, enemy, 0x680);
OFF(Act, mailAddData, 0x684);
OFF(Act, work, 0x688);
OFF(Act, addData, 0x68C);
OFF(Act, flyClip, 0x690);
#endif

/* GenGeo: overlay, ico2/common/include/typedef.h:1662, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(GenGeo, scale, 0x0);
OFF(GenGeo, rot, 0xC);
OFF(GenGeo, pos, 0x18);
OFF(GenGeo, proc, 0x24);
OFF(GenGeo, outGObj, 0x28);
OFF(GenGeo, mdl, 0x2C);
OFF(GenGeo, accessary, 0x30);
OFF(GenGeo, action, 0x34);
OFF(GenGeo, initArg, 0x38);
OFF(GenGeo, word3C, 0x3C);
OFF(GenGeo, procPri, 0x40);
OFF(GenGeo, reviveCount, 0x42);
OFF(GenGeo, parent, 0x44);
OFF(GenGeo, kind, 0x46);
OFF(GenGeo, light, 0x47);
OFF(GenGeo, flags, 0x48);
SIZE(GenGeo, 0x4C); /* comment */
#endif

/* OaRecB: overlay, ico2/common/include/typedef.h:1684 */
OFF(OaRecB, baseMode, 0x0);
OFF(OaRecB, anim2, 0x4);
OFF(OaRecB, word8, 0x8);
OFF(OaRecB, mode, 0xC);
OFF(OaRecB, flags, 0x10);

/* McFileInfo: save, ico2/common/include/typedef.h:1702 */
OFF(McFileInfo, stage, 0x0);
OFF(McFileInfo, cleared, 0x4);
OFF(McFileInfo, playTime, 0x8);
OFF(McFileInfo, sofa, 0xC);
OFF(McFileInfo, word10, 0x10);

/* McProductFile: save, ico2/common/include/typedef.h:1710 */
OFF(McProductFile, file, 0x0);
OFF(McProductFile, soundMode, 0x190);
OFF(McProductFile, outputMode, 0x194);
OFF(McProductFile, vibration, 0x198);
OFF(McProductFile, controlType, 0x19C);
OFF(McProductFile, padConf, 0x1A0);
OFF(McProductFile, fileNo, 0x1E0);
OFF(McProductFile, serial, 0x1E4);
OFF(McProductFile, cameraMove, 0x1E8);
OFF(McProductFile, palMode, 0x1EC);
SIZE(McProductFile, 0x1F0); /* config */

/* McMgr: runtime, ico2/common/include/typedef.h:1743 */
#if ICO_LAYOUT_EE
OFF(McMgr, flags, 0x0);
OFF(McMgr, port, 0x8);
OFF(McMgr, slot, 0xC);
OFF(McMgr, result, 0x10);
OFF(McMgr, type, 0x14);
OFF(McMgr, free, 0x18);
OFF(McMgr, cardState, 0x1C);
OFF(McMgr, format, 0x20);
OFF(McMgr, segment, 0x24);
OFF(McMgr, fd, 0x28);
OFF(McMgr, openMode, 0x2C);
OFF(McMgr, cmd, 0x30);
OFF(McMgr, size, 0x34);
OFF(McMgr, pos, 0x38);
OFF(McMgr, end, 0x3C);
OFF(McMgr, fileNo, 0x40);
OFF(McMgr, dirCount, 0x44);
OFF(McMgr, segArg, 0x48);
OFF(McMgr, sum, 0x4C);
OFF(McMgr, readSum, 0x50);
OFF(McMgr, buf, 0x54);
OFF(McMgr, dirName, 0x454);
OFF(McMgr, pwd, 0x468);
OFF(McMgr, path, 0x47C);
OFF(McMgr, dir, 0x4C0);
OFF(McMgr, mask, 0x9C0);
SIZE(McMgr, 0xA00); /* comment */
#endif

/* HandClInfo: runtime, ico2/fumi/include/act-game.h:18 */
#if ICO_LAYOUT_EE
OFF(HandClInfo, on, 0x0);
OFF(HandClInfo, hit, 0x1);
OFF(HandClInfo, attr, 0x2);
OFF(HandClInfo, pad3, 0x3);
OFF(HandClInfo, orient, 0x10);
OFF(HandClInfo, hit2, 0x20);
OFF(HandClInfo, attr2, 0x21);
OFF(HandClInfo, pad22, 0x22);
OFF(HandClInfo, orient2, 0x30);
#endif

/* ActEffRec: runtime, ico2/fumi/include/act-game.h:32 */
#if ICO_LAYOUT_EE
OFF(ActEffRec, pos, 0x0);
OFF(ActEffRec, dir, 0x10);
OFF(ActEffRec, power, 0x20);
OFF(ActEffRec, frames, 0x24);
OFF(ActEffRec, kind, 0x28);
OFF(ActEffRec, pad2C, 0x2C);
#endif

/* ActWork: runtime, ico2/fumi/include/act-game.h:44 */
#if ICO_LAYOUT_EE
OFF(ActWork, paraTbl, 0x0);
OFF(ActWork, pad158, 0x158);
OFF(ActWork, defIkRate0, 0x320);
OFF(ActWork, defIkRate1, 0x324);
OFF(ActWork, defIkRate2, 0x328);
OFF(ActWork, boyDist, 0x32C);
OFF(ActWork, escortOffset, 0x330);
OFF(ActWork, disappearSpeed, 0x334);
OFF(ActWork, fallDamageHeight, 0x338);
OFF(ActWork, ropeClimbHeight, 0x33C);
OFF(ActWork, stickMag, 0x340);
OFF(ActWork, lockedMaxRotate, 0x344);
OFF(ActWork, parallelInterp, 0x348);
OFF(ActWork, pad34C, 0x34C);
OFF(ActWork, padWish, 0x350);
OFF(ActWork, fallDir, 0x360);
OFF(ActWork, hideObj, 0x370);
OFF(ActWork, floorObj, 0x374);
OFF(ActWork, bga, 0x378);
OFF(ActWork, downTimer, 0x37C);
OFF(ActWork, brainTimer, 0x380);
OFF(ActWork, turnTimer, 0x384);
OFF(ActWork, turnTimer2, 0x388);
OFF(ActWork, noInterpTimer, 0x38C);
OFF(ActWork, wishHoldTimer, 0x390);
OFF(ActWork, leverTimer, 0x394);
OFF(ActWork, nakaBossCount, 0x398);
OFF(ActWork, carryGirlFrames, 0x39C);
OFF(ActWork, sofaTimer, 0x3A0);
OFF(ActWork, sofaRestTimer, 0x3A4);
OFF(ActWork, orientFrames, 0x3A8);
OFF(ActWork, timer3AC, 0x3AC);
OFF(ActWork, turnMailWait, 0x3B0);
OFF(ActWork, jumpTimer, 0x3B4);
OFF(ActWork, footIkFrames, 0x3B8);
OFF(ActWork, bit37Frames, 0x3BC);
OFF(ActWork, bit38Frames, 0x3C0);
OFF(ActWork, mailB1Timer, 0x3C4);
OFF(ActWork, ditchTimer, 0x3C8);
OFF(ActWork, bellowWall400, 0x3CC);
OFF(ActWork, bellowWall3000, 0x3D8);
OFF(ActWork, dangerObj, 0x3E4);
OFF(ActWork, pad3E8, 0x3E8);
OFF(ActWork, hideDirX, 0x3F0);
OFF(ActWork, hideDirY, 0x3F4);
OFF(ActWork, hideDirZ, 0x3F8);
OFF(ActWork, pad3FC, 0x3FC);
OFF(ActWork, ropeCage, 0x400);
OFF(ActWork, pad404, 0x404);
OFF(ActWork, handPosX, 0x410);
OFF(ActWork, handPosY, 0x414);
OFF(ActWork, handPosZ, 0x418);
OFF(ActWork, handPosW, 0x41C);
OFF(ActWork, lastPosX, 0x420);
OFF(ActWork, lastPosY, 0x424);
OFF(ActWork, lastPosZ, 0x428);
OFF(ActWork, pad42C, 0x42C);
OFF(ActWork, velX, 0x430);
OFF(ActWork, velY, 0x434);
OFF(ActWork, velZ, 0x438);
OFF(ActWork, pad43C, 0x43C);
OFF(ActWork, speed, 0x440);
OFF(ActWork, slowFrames, 0x444);
OFF(ActWork, stopFrames, 0x448);
OFF(ActWork, pad44C, 0x44C);
OFF(ActWork, noMoveFrames, 0x450);
OFF(ActWork, enemyFlags, 0x454);
OFF(ActWork, pad458, 0x458);
OFF(ActWork, genTarget, 0x460);
OFF(ActWork, motherLabel, 0x464);
OFF(ActWork, motherGObj, 0x468);
OFF(ActWork, pad46C, 0x46C);
OFF(ActWork, hangOrient, 0x470);
OFF(ActWork, pad47C, 0x47C);
OFF(ActWork, cliffReq, 0x480);
OFF(ActWork, pinchPosX, 0x4A0);
OFF(ActWork, pinchPosY, 0x4A4);
OFF(ActWork, pinchPosZ, 0x4A8);
OFF(ActWork, pad4AC, 0x4AC);
OFF(ActWork, pinchFrames, 0x4B0);
OFF(ActWork, pad4B4, 0x4B4);
OFF(ActWork, handrailOrient, 0x4C0);
OFF(ActWork, basePosSet, 0x4D0);
OFF(ActWork, pad4D4, 0x4D4);
OFF(ActWork, basePos, 0x4E0);
OFF(ActWork, boxSideSet, 0x4F0);
OFF(ActWork, pad4F1, 0x4F1);
OFF(ActWork, boxSidePos, 0x500);
OFF(ActWork, boyOrient, 0x510);
OFF(ActWork, hintPosX, 0x520);
OFF(ActWork, hintPosY, 0x524);
OFF(ActWork, hintPosZ, 0x528);
OFF(ActWork, pad52C, 0x52C);
OFF(ActWork, boxDir, 0x530);
OFF(ActWork, handCl, 0x540);
OFF(ActWork, wayReq, 0x580);
OFF(ActWork, pad638, 0x638);
OFF(ActWork, view, 0x720);
OFF(ActWork, viewState, 0x800);
OFF(ActWork, pad804, 0x804);
OFF(ActWork, effRec, 0x810);
OFF(ActWork, emgPosX, 0x8A0);
OFF(ActWork, emgPosY, 0x8A4);
OFF(ActWork, emgPosZ, 0x8A8);
OFF(ActWork, pad8AC, 0x8AC);
OFF(ActWork, intrReq, 0x8B0);
OFF(ActWork, pad8D0, 0x8D0);
OFF(ActWork, wayHold, 0x8E0);
OFF(ActWork, pad8E4, 0x8E4);
OFF(ActWork, wayDirX, 0x8F0);
OFF(ActWork, wayDirY, 0x8F4);
OFF(ActWork, wayDirZ, 0x8F8);
OFF(ActWork, pad8FC, 0x8FC);
OFF(ActWork, modeHist, 0x900);
OFF(ActWork, frameHist, 0x928);
OFF(ActWork, prevHist, 0x950);
#endif

/* LookTarget: overlay, ico2/fumi/include/act-game.h:282 */
OFF(LookTarget, kind, 0x0);
SIZE(LookTarget, 0xC); /* comment */

/* ParallelMotionRow: overlay, ico2/fumi/include/act-parallel-control.h:22 */
OFF(ParallelMotionRow, motion, 0x0);
SIZE(ParallelMotionRow, 0xB0); /* comment */

/* ActModeRec: overlay, ico2/fumi/include/act.h:44, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(ActModeRec, ent, 0x0);
OFF(ActModeRec, name, 0x24);
OFF(ActModeRec, intrList, 0x44);
OFF(ActModeRec, mail, 0x48);
SIZE(ActModeRec, 0x50); /* comment */
#endif

/* IntrMail: overlay, ico2/fumi/include/act.h:79, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(IntrMail, motion, 0x0);
OFF(IntrMail, extra, 0x4);
OFF(IntrMail, handler, 0x8);
OFF(IntrMail, accept, 0xC);
OFF(IntrMail, kind, 0x10);
OFF(IntrMail, mode, 0x12);
OFF(IntrMail, flags, 0x14);
SIZE(IntrMail, 0x18); /* comment */
#endif

/* AdpcmOpenReq: runtime, ico2/fumi/include/adpcm_init.h:19 */
#if ICO_LAYOUT_EE
OFF(AdpcmOpenReq, mode, 0x0);
OFF(AdpcmOpenReq, id, 0x4);
OFF(AdpcmOpenReq, ch, 0x8);
OFF(AdpcmOpenReq, iopBuf, 0xC);
OFF(AdpcmOpenReq, loopNum, 0x10);
OFF(AdpcmOpenReq, bg, 0x14);
#endif

/* AdpcmChReq: runtime, ico2/fumi/include/adpcm_init.h:34 */
#if ICO_LAYOUT_EE
OFF(AdpcmChReq, ch, 0x0);
OFF(AdpcmChReq, attr, 0x4);
OFF(AdpcmChReq, iopAddr, 0x8);
OFF(AdpcmChReq, iopSize, 0xC);
OFF(AdpcmChReq, spuAddr, 0x10);
OFF(AdpcmChReq, vol, 0x14);
#endif

/* AdpcmStream: runtime, ico2/fumi/include/adpcm_init.h:43 */
#if ICO_LAYOUT_EE
OFF(AdpcmStream, used, 0x0);
OFF(AdpcmStream, n, 0x4);
OFF(AdpcmStream, ch, 0x8);
OFF(AdpcmStream, seekSize, 0x10);
OFF(AdpcmStream, pitch, 0x14);
OFF(AdpcmStream, iopBuf, 0x18);
OFF(AdpcmStream, ringSize, 0x1C);
OFF(AdpcmStream, loopStart, 0x20);
OFF(AdpcmStream, dataSize, 0x24);
OFF(AdpcmStream, bg, 0x28);
OFF(AdpcmStream, mask, 0x30);
OFF(AdpcmStream, chAttr, 0x38);
OFF(AdpcmStream, volL, 0x3C);
OFF(AdpcmStream, volR, 0x40);
OFF(AdpcmStream, fadeStep, 0x44);
OFF(AdpcmStream, loopNum, 0x46);
OFF(AdpcmStream, loopCount, 0x48);
OFF(AdpcmStream, pad4A, 0x4A);
OFF(AdpcmStream, lastAddr, 0x4C);
OFF(AdpcmStream, remain, 0x50);
OFF(AdpcmStream, pad54, 0x54);
#endif

/* AdpcmDataRec: overlay, ico2/fumi/include/adpcm_init.h:95 */
OFF(AdpcmDataRec, path, 0x0);
OFF(AdpcmDataRec, loopStart, 0x30);
OFF(AdpcmDataRec, sectors, 0x34);
OFF(AdpcmDataRec, pitch, 0x38);
OFF(AdpcmDataRec, channels, 0x3C);
SIZE(AdpcmDataRec, 0x40); /* comment */

/* CdvdBgReq: runtime, ico2/fumi/include/cdvd.h:21 */
#if ICO_LAYOUT_EE
OFF(CdvdBgReq, name, 0x0);
OFF(CdvdBgReq, readFunc, 0x100);
OFF(CdvdBgReq, readArg, 0x104);
OFF(CdvdBgReq, flags, 0x108);
OFF(CdvdBgReq, size, 0x10C);
OFF(CdvdBgReq, pos, 0x110);
OFF(CdvdBgReq, lsn, 0x114);
OFF(CdvdBgReq, readyFunc, 0x118);
OFF(CdvdBgReq, resumeFunc, 0x11C);
OFF(CdvdBgReq, cbArg, 0x120);
OFF(CdvdBgReq, closeFunc, 0x124);
OFF(CdvdBgReq, closeArg, 0x128);
#endif

/* PackKind: overlay, ico2/fumi/include/cdvd.h:89, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(PackKind, ext, 0x0);
OFF(PackKind, func, 0x20);
SIZE(PackKind, 0x24); /* comment */
#endif

/* IdlingDef: overlay, ico2/fumi/include/commonact.h:54 */
OFF(IdlingDef, motion, 0x0);
SIZE(IdlingDef, 0xC); /* comment */

/* IdleRangeRec: overlay, ico2/fumi/include/commonact.h:62 */
OFF(IdleRangeRec, idleMotion, 0x0);
OFF(IdleRangeRec, orientRow, 0x4);
OFF(IdleRangeRec, orientRow2, 0x8);
OFF(IdleRangeRec, orientFirst, 0xC);
OFF(IdleRangeRec, orientEnd, 0x10);
SIZE(IdleRangeRec, 0x14); /* comment */

/* ClingRec: overlay, ico2/fumi/include/commonact.h:74 */
OFF(ClingRec, rot, 0x0);
OFF(ClingRec, pos, 0xC);
OFF(ClingRec, mode, 0x18);
OFF(ClingRec, motion, 0x1C);
OFF(ClingRec, node, 0x20);
SIZE(ClingRec, 0x24); /* comment */

/* BecPair: overlay, ico2/fumi/include/commonact.h:85 */
OFF(BecPair, mot, 0x0);
OFF(BecPair, req, 0x4);
SIZE(BecPair, 0x8); /* comment */

/* BossPart: runtime, ico2/fumi/include/enemy_act.h:43 */
#if ICO_LAYOUT_EE
OFF(BossPart, pos, 0x0);
OFF(BossPart, effect, 0x10);
OFF(BossPart, id, 0x14);
OFF(BossPart, timer, 0x18);
OFF(BossPart, busy, 0x1C);
OFF(BossPart, alive, 0x1D);
OFF(BossPart, pad1E, 0x1E);
SIZE(BossPart, 0x20); /* comment */
#endif

/* EnemyBattleWork: runtime, ico2/fumi/include/enemy_act.h:56 */
#if ICO_LAYOUT_EE
OFF(EnemyBattleWork, pad0, 0x0);
OFF(EnemyBattleWork, speedRatioPri, 0x54);
OFF(EnemyBattleWork, speedRatio, 0x58);
OFF(EnemyBattleWork, paraTimer, 0x5C);
OFF(EnemyBattleWork, paraRandom, 0x60);
OFF(EnemyBattleWork, pad64, 0x64);
OFF(EnemyBattleWork, corrPosX, 0x70);
OFF(EnemyBattleWork, corrPosY, 0x74);
OFF(EnemyBattleWork, corrPosZ, 0x78);
OFF(EnemyBattleWork, pad7C, 0x7C);
OFF(EnemyBattleWork, corrDirX, 0x80);
OFF(EnemyBattleWork, corrDirY, 0x84);
OFF(EnemyBattleWork, corrDirZ, 0x88);
OFF(EnemyBattleWork, pad8C, 0x8C);
OFF(EnemyBattleWork, corrDstX, 0x90);
OFF(EnemyBattleWork, corrDstY, 0x94);
OFF(EnemyBattleWork, corrDstZ, 0x98);
OFF(EnemyBattleWork, pad9C, 0x9C);
OFF(EnemyBattleWork, corrDstDirX, 0xA0);
OFF(EnemyBattleWork, corrDstDirY, 0xA4);
OFF(EnemyBattleWork, corrDstDirZ, 0xA8);
OFF(EnemyBattleWork, padAC, 0xAC);
OFF(EnemyBattleWork, corrFrames, 0xB0);
OFF(EnemyBattleWork, corrCount, 0xB4);
OFF(EnemyBattleWork, corrMode, 0xB8);
OFF(EnemyBattleWork, corrFlags, 0xBC);
OFF(EnemyBattleWork, jumpOrient, 0xC0);
OFF(EnemyBattleWork, liftToggle, 0xC4);
OFF(EnemyBattleWork, liftPhase, 0xC8);
OFF(EnemyBattleWork, liftLevel, 0xCC);
OFF(EnemyBattleWork, floorAttrOff, 0xD0);
OFF(EnemyBattleWork, liftTimer, 0xD4);
OFF(EnemyBattleWork, padD8, 0xD8);
OFF(EnemyBattleWork, hitDir, 0xE0);
OFF(EnemyBattleWork, hitNodes, 0xF0);
OFF(EnemyBattleWork, lwsEffect, 0x1B8);
OFF(EnemyBattleWork, pad1BC, 0x1BC);
OFF(EnemyBattleWork, ropeCliffX, 0x1C0);
OFF(EnemyBattleWork, ropeCliffY, 0x1C4);
OFF(EnemyBattleWork, ropeCliffZ, 0x1C8);
OFF(EnemyBattleWork, pad1CC, 0x1CC);
OFF(EnemyBattleWork, frontPosX, 0x1D0);
OFF(EnemyBattleWork, frontPosY, 0x1D4);
OFF(EnemyBattleWork, frontPosZ, 0x1D8);
OFF(EnemyBattleWork, pad1DC, 0x1DC);
OFF(EnemyBattleWork, sizeClass, 0x1E8);
OFF(EnemyBattleWork, paraStatus, 0x1F0);
OFF(EnemyBattleWork, clingNode, 0x1F4);
OFF(EnemyBattleWork, attackChance, 0x1F8);
OFF(EnemyBattleWork, attackChance2, 0x1FC);
OFF(EnemyBattleWork, bodyslamMail, 0x200);
OFF(EnemyBattleWork, bossLife, 0x20C);
OFF(EnemyBattleWork, target, 0x218);
OFF(EnemyBattleWork, clingReq, 0x21C);
OFF(EnemyBattleWork, clingTarget, 0x220);
OFF(EnemyBattleWork, liftedObj, 0x22C);
OFF(EnemyBattleWork, readyPosX, 0x230);
OFF(EnemyBattleWork, readyPosY, 0x234);
OFF(EnemyBattleWork, readyPosZ, 0x238);
OFF(EnemyBattleWork, pad23C, 0x23C);
OFF(EnemyBattleWork, readyDirX, 0x240);
OFF(EnemyBattleWork, readyDirY, 0x244);
OFF(EnemyBattleWork, readyDirZ, 0x248);
OFF(EnemyBattleWork, pad24C, 0x24C);
OFF(EnemyBattleWork, sofaWake, 0x250);
OFF(EnemyBattleWork, sofaWakeTime, 0x254);
OFF(EnemyBattleWork, dirSmoothFrames, 0x258);
OFF(EnemyBattleWork, dirSmoothFrames2, 0x25C);
OFF(EnemyBattleWork, clingedFrames, 0x260);
OFF(EnemyBattleWork, pad264, 0x264);
OFF(EnemyBattleWork, slipDirX, 0x270);
OFF(EnemyBattleWork, slipDirY, 0x274);
OFF(EnemyBattleWork, slipDirZ, 0x278);
OFF(EnemyBattleWork, pad27C, 0x27C);
OFF(EnemyBattleWork, slipFront, 0x280);
OFF(EnemyBattleWork, pad281, 0x281);
OFF(EnemyBattleWork, ladderUpStep, 0x290);
OFF(EnemyBattleWork, ladderDownStep, 0x294);
OFF(EnemyBattleWork, word298, 0x298);
OFF(EnemyBattleWork, stoneLevel, 0x29C);
OFF(EnemyBattleWork, stonePair, 0x2A0);
OFF(EnemyBattleWork, word2A4, 0x2A4);
OFF(EnemyBattleWork, stoneHitNoWeapon, 0x2A8);
OFF(EnemyBattleWork, stoneHitWeapon, 0x2AC);
OFF(EnemyBattleWork, word2B0, 0x2B0);
OFF(EnemyBattleWork, pad2B4, 0x2B4);
OFF(EnemyBattleWork, word2C0, 0x2C0);
OFF(EnemyBattleWork, holdObj, 0x2C4);
OFF(EnemyBattleWork, pad2C8, 0x2C8);
OFF(EnemyBattleWork, holdPoint, 0x2D0);
OFF(EnemyBattleWork, rescueObj, 0x2E0);
OFF(EnemyBattleWork, pad2E4, 0x2E4);
OFF(EnemyBattleWork, rescueBoyPos, 0x2F0);
OFF(EnemyBattleWork, rescueGirlPos, 0x300);
OFF(EnemyBattleWork, boxBarSound, 0x310);
OFF(EnemyBattleWork, handConnect, 0x314);
OFF(EnemyBattleWork, handDisconnect, 0x31C);
OFF(EnemyBattleWork, pad324, 0x324);
OFF(EnemyBattleWork, climbOrient, 0x330);
OFF(EnemyBattleWork, climbPos, 0x340);
OFF(EnemyBattleWork, climbCol, 0x350);
OFF(EnemyBattleWork, climbObj, 0x35C);
OFF(EnemyBattleWork, boss, 0x360);
#endif

/* FcWallEnt: overlay, ico2/fumi/include/fieldCollision.h:35 */
OFF(FcWallEnt, pt, 0x0);
OFF(FcWallEnt, height, 0x40);
OFF(FcWallEnt, angle, 0x44);
OFF(FcWallEnt, pad46, 0x46);
OFF(FcWallEnt, attr, 0x48);
OFF(FcWallEnt, normal, 0x4C);
SIZE(FcWallEnt, 0x50); /* config */

/* FcColl: overlay, ico2/fumi/include/fieldCollision.h:54 */
OFF(FcColl, pad0, 0x0);
OFF(FcColl, count, 0x8);
OFF(FcColl, nfloor, 0xC);
OFF(FcColl, wcl, 0x10);
OFF(FcColl, fcl, 0x14);
OFF(FcColl, wblk, 0x18);
OFF(FcColl, fblk, 0x1C);
OFF(FcColl, ofs, 0x20);

/* FcFloorEnt: overlay, ico2/fumi/include/fieldCollision.h:73 */
OFF(FcFloorEnt, v, 0x0);
OFF(FcFloorEnt, nx, 0x40);
OFF(FcFloorEnt, d, 0x50);
OFF(FcFloorEnt, nex, 0x54);
OFF(FcFloorEnt, pad58, 0x58);
OFF(FcFloorEnt, attr, 0x60);
OFF(FcFloorEnt, pad64, 0x64);
SIZE(FcFloorEnt, 0x70); /* comment */

/* EscapeRange: overlay, ico2/fumi/include/girl_act.h:66 */
OFF(EscapeRange, lo, 0x0);
OFF(EscapeRange, hi, 0x4);
SIZE(EscapeRange, 0x8); /* comment */

/* EscortPoint: overlay, ico2/fumi/include/girl_act.h:73 */
OFF(EscortPoint, pos, 0x0);
OFF(EscortPoint, area, 0xC);
OFF(EscortPoint, point, 0x10);
OFF(EscortPoint, range, 0x14);
OFF(EscortPoint, rate, 0x18);
SIZE(EscortPoint, 0x1C); /* comment */

/* GProc: runtime, ico2/fumi/include/gobj_process.h:16 */
#if ICO_LAYOUT_EE
OFF(GProc, self, 0x0);
OFF(GProc, owner, 0x4);
OFF(GProc, prev, 0x8);
OFF(GProc, next, 0xC);
OFF(GProc, noThread, 0x10);
OFF(GProc, priority, 0x14);
OFF(GProc, active, 0x18);
OFF(GProc, func, 0x1C);
OFF(GProc, arg, 0x20);
OFF(GProc, thread, 0x24);
SIZE(GProc, 0x94); /* comment */
#endif

/* JimakuSub: runtime, ico2/fumi/include/jimaku.h:15 */
#if ICO_LAYOUT_EE
OFF(JimakuSub, pad0, 0x0);
OFF(JimakuSub, block, 0x2C);
OFF(JimakuSub, n, 0x30);
OFF(JimakuSub, ringPos, 0x34);
OFF(JimakuSub, jump, 0x38);
OFF(JimakuSub, cur, 0x3C);
OFF(JimakuSub, bg, 0x40);
#endif

/* JimakuArg: runtime, ico2/fumi/include/jimaku.h:26 */
#if ICO_LAYOUT_EE
OFF(JimakuArg, cmd, 0x0);
OFF(JimakuArg, pad4, 0x4);
OFF(JimakuArg, done, 0x8);
OFF(JimakuArg, sub, 0xC);
#endif

/* JimakuFileName: overlay, ico2/fumi/include/jimaku.h:51 */
OFF(JimakuFileName, path, 0x0);
SIZE(JimakuFileName, 0x20); /* comment */

/* IconFile: overlay, ico2/fumi/include/mcard.h:43 */
OFF(IconFile, name, 0x0);
OFF(IconFile, size, 0x20);
SIZE(IconFile, 0x24); /* comment */

/* IosMemPart: runtime, ico2/fumi/include/memory.h:19 */
#if ICO_LAYOUT_EE
OFF(IosMemPart, tag, 0x0);
OFF(IosMemPart, name, 0x10);
OFF(IosMemPart, parent, 0x20);
OFF(IosMemPart, next, 0x24);
OFF(IosMemPart, child, 0x28);
OFF(IosMemPart, nused, 0x2C);
OFF(IosMemPart, top, 0x30);
OFF(IosMemPart, free, 0x34);
OFF(IosMemPart, start, 0x38);
OFF(IosMemPart, end, 0x3C);
OFF(IosMemPart, total, 0x40);
OFF(IosMemPart, head, 0x44);
SIZE(IosMemPart, 0x48); /* config */
#endif

/* IosMemNode: runtime, ico2/fumi/include/memory.h:35 */
#if ICO_LAYOUT_EE
OFF(IosMemNode, tag, 0x0);
OFF(IosMemNode, name, 0x10);
OFF(IosMemNode, prev, 0x20);
OFF(IosMemNode, next, 0x24);
OFF(IosMemNode, free_prev, 0x28);
OFF(IosMemNode, free_next, 0x2C);
OFF(IosMemNode, part, 0x30);
OFF(IosMemNode, size, 0x34);
OFF(IosMemNode, line, 0x38);
SIZE(IosMemNode, 0x40); /* config */
#endif

/* IosMsgQueue: runtime, ico2/fumi/include/message.h:23 */
#if ICO_LAYOUT_EE
OFF(IosMsgQueue, buf, 0x0);
OFF(IosMsgQueue, rd, 0x4);
OFF(IosMsgQueue, num, 0x8);
OFF(IosMsgQueue, size, 0xC);
OFF(IosMsgQueue, head, 0x10);
OFF(IosMsgQueue, sem, 0x14);
OFF(IosMsgQueue, sema, 0x2C);
#endif

/* IosPadBuf: runtime, ico2/fumi/include/pad.h:17 */
#if ICO_LAYOUT_EE
OFF(IosPadBuf, pad0, 0x0);
OFF(IosPadBuf, hi, 0x2);
OFF(IosPadBuf, lo, 0x3);
OFF(IosPadBuf, rx, 0x4);
OFF(IosPadBuf, ry, 0x5);
OFF(IosPadBuf, lx, 0x6);
OFF(IosPadBuf, ly, 0x7);
OFF(IosPadBuf, pad8, 0x8);
#endif

/* IosPadShock: runtime, ico2/fumi/include/pad.h:31 */
#if ICO_LAYOUT_EE
OFF(IosPadShock, box, 0x0);
OFF(IosPadShock, motor0, 0x10);
OFF(IosPadShock, motor1, 0x11);
OFF(IosPadShock, pad12, 0x12);
OFF(IosPadShock, motor, 0x14);
#endif

/* IosPadDevRec: runtime, ico2/fumi/include/pad.h:39 */
#if ICO_LAYOUT_EE
OFF(IosPadDevRec, port, 0x0);
OFF(IosPadDevRec, slot, 0x4);
OFF(IosPadDevRec, termId, 0x8);
OFF(IosPadDevRec, idx, 0xC);
OFF(IosPadDevRec, buf, 0x10);
OFF(IosPadDevRec, pad50, 0x50);
OFF(IosPadDevRec, state, 0x180);
OFF(IosPadDevRec, phase, 0x184);
OFF(IosPadDevRec, errCount, 0x188);
OFF(IosPadDevRec, lastTermId, 0x18C);
OFF(IosPadDevRec, pad190, 0x190);
OFF(IosPadDevRec, error, 0x194);
OFF(IosPadDevRec, act, 0x198);
OFF(IosPadDevRec, pad19E, 0x19E);
OFF(IosPadDevRec, shock, 0x1A4);
OFF(IosPadDevRec, flags, 0x1C0);
#endif

/* IosPadCtx: runtime, ico2/fumi/include/pad.h:66 */
#if ICO_LAYOUT_EE
OFF(IosPadCtx, dev, 0x0);
OFF(IosPadCtx, conf, 0x4);
OFF(IosPadCtx, now, 0x8);
OFF(IosPadCtx, trg, 0xC);
OFF(IosPadCtx, rel, 0x10);
OFF(IosPadCtx, word14, 0x14);
OFF(IosPadCtx, now2, 0x18);
OFF(IosPadCtx, trg2, 0x1C);
OFF(IosPadCtx, rel2, 0x20);
OFF(IosPadCtx, word24, 0x24);
OFF(IosPadCtx, pad28, 0x28);
SIZE(IosPadCtx, 0x60); /* comment */
#endif

/* IosPadStick: runtime, ico2/fumi/include/pad.h:84 */
#if ICO_LAYOUT_EE
OFF(IosPadStick, x, 0x0);
OFF(IosPadStick, y, 0x4);
OFF(IosPadStick, angle, 0x8);
OFF(IosPadStick, dx, 0xC);
OFF(IosPadStick, dz, 0x10);
OFF(IosPadStick, mag, 0x14);
#endif

/* PadAct: runtime, ico2/fumi/include/pad.h:99 */
#if ICO_LAYOUT_EE
OFF(PadAct, key, 0x0);
OFF(PadAct, box, 0x4);
OFF(PadAct, voice, 0x8);
OFF(PadAct, prm, 0xC);
OFF(PadAct, life, 0x10);
OFF(PadAct, tick, 0x12);
OFF(PadAct, volume, 0x14);
#endif

/* PadActDef: overlay, ico2/fumi/include/pad.h:133 */
OFF(PadActDef, word0, 0x0);
OFF(PadActDef, voice, 0x4);
OFF(PadActDef, life, 0x6);
SIZE(PadActDef, 0x8); /* comment */

/* SqEntry: runtime, ico2/fumi/include/s_init.h:25 */
#if ICO_LAYOUT_EE
OFF(SqEntry, num, 0x0);
OFF(SqEntry, bank, 0x2);
OFF(SqEntry, mode, 0x4);
OFF(SqEntry, seg, 0x6);
OFF(SqEntry, bd, 0x8);
OFF(SqEntry, hd, 0xC);
OFF(SqEntry, sq, 0x10);
OFF(SqEntry, pad14, 0x14);
OFF(SqEntry, spu.buf.addr, 0x18);
OFF(SqEntry, spu.buf.size, 0x1C);
OFF(SqEntry, spu.chMask, 0x18);
OFF(SqEntry, seMask, 0x20);
OFF(SqEntry, vab, 0x28);
OFF(SqEntry, stream, 0x2C);
SIZE(SqEntry, 0x30); /* comment */
#endif

/* SeDef: overlay, ico2/fumi/include/s_init.h:100, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(SeDef, name, 0x0);
OFF(SeDef, kind, 0x20);
OFF(SeDef, volume, 0x24);
OFF(SeDef, mail, 0x28);
OFF(SeDef, check, 0x2C);
OFF(SeDef, range, 0x30);
OFF(SeDef, mailArg, 0x34);
OFF(SeDef, shock, 0x36);
SIZE(SeDef, 0x3C); /* comment */
#endif

/* SeEnvDef: overlay, ico2/fumi/include/s_init.h:123, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(SeEnvDef, se, 0x0);
OFF(SeEnvDef, proc, 0x4);
OFF(SeEnvDef, volumeRate, 0x8);
OFF(SeEnvDef, maxVolumeRange, 0xC);
OFF(SeEnvDef, attenuator, 0x10);
OFF(SeEnvDef, volumeLength, 0x14);
SIZE(SeEnvDef, 0x1C); /* comment */
#endif

/* SeBank: overlay, ico2/fumi/include/s_init.h:144 */
OFF(SeBank, hdPath, 0x0);
OFF(SeBank, bdPath, 0x30);
SIZE(SeBank, 0x64); /* comment */

/* SeKind: overlay, ico2/fumi/include/s_init.h:155 */
OFF(SeKind, num, 0x0);
OFF(SeKind, prog, 0x2);
OFF(SeKind, tone, 0x4);
OFF(SeKind, idx, 0x6);
SIZE(SeKind, 0x8); /* comment */

/* ShockParam: runtime, ico2/fumi/include/shockdriver.h:15 */
#if ICO_LAYOUT_EE
OFF(ShockParam, voice, 0x0);
OFF(ShockParam, waveId, 0x1);
OFF(ShockParam, volume, 0x2);
OFF(ShockParam, timeScale, 0x3);
#endif

/* VibDecode: runtime, ico2/fumi/include/shockdriver.h:24 */
#if ICO_LAYOUT_EE
OFF(VibDecode, buf, 0x0);
OFF(VibDecode, pos, 0x4);
OFF(VibDecode, acc, 0x6);
OFF(VibDecode, prev, 0x8);
OFF(VibDecode, len, 0xA);
OFF(VibDecode, time, 0xC);
OFF(VibDecode, cnt, 0xE);
#endif

/* SHOCKREQUEST: runtime, ico2/fumi/include/shockdriver.h:38 */
#if ICO_LAYOUT_EE
OFF(SHOCKREQUEST, flags, 0x0);
OFF(SHOCKREQUEST, waveId, 0x1);
OFF(SHOCKREQUEST, volume, 0x2);
OFF(SHOCKREQUEST, timeScale, 0x3);
OFF(SHOCKREQUEST, shot, 0x4);
OFF(SHOCKREQUEST, wave, 0x14);
OFF(SHOCKREQUEST, waveFrom, 0x24);
OFF(SHOCKREQUEST, waveTo, 0x25);
OFF(SHOCKREQUEST, shotRep, 0x26);
OFF(SHOCKREQUEST, waveRep, 0x27);
OFF(SHOCKREQUEST, key, 0x28);
OFF(SHOCKREQUEST, arg, 0x2C);
OFF(SHOCKREQUEST, prev, 0x30);
OFF(SHOCKREQUEST, next, 0x34);
OFF(SHOCKREQUEST, voice, 0x38);
OFF(SHOCKREQUEST, pad39, 0x39);
OFF(SHOCKREQUEST, org, 0x3C);
SIZE(SHOCKREQUEST, 0x40); /* comment */
#endif

/* ShockRequestBox: runtime, ico2/fumi/include/shockdriver.h:67 */
#if ICO_LAYOUT_EE
OFF(ShockRequestBox, head, 0x0);
OFF(ShockRequestBox, alloc, 0x4);
OFF(ShockRequestBox, free, 0x8);
OFF(ShockRequestBox, pool, 0xC);
#endif

/* ShockReq: runtime, ico2/fumi/include/shockdriver.h:76 */
#if ICO_LAYOUT_EE
OFF(ShockReq, out, 0x0);
OFF(ShockReq, acc, 0x2);
OFF(ShockReq, type, 0x4);
OFF(ShockReq, val, 0x5);
#endif

/* ShockVoiceSet: runtime, ico2/fumi/include/shockdriver.h:88 */
#if ICO_LAYOUT_EE
OFF(ShockVoiceSet, top, 0x0);
OFF(ShockVoiceSet, shot, 0x4);
OFF(ShockVoiceSet, wave, 0x8);
OFF(ShockVoiceSet, voice, 0xC);
#endif

/* ShockVoiceFile: runtime, ico2/fumi/include/shockdriver.h:101 */
#if ICO_LAYOUT_EE
OFF(ShockVoiceFile, set, 0x0);
OFF(ShockVoiceFile, image, 0x10);
#endif

/* IOSThread: runtime, ico2/fumi/include/thread.h:14 */
#if ICO_LAYOUT_EE
OFF(IOSThread, param, 0x0);
OFF(IOSThread, id, 0x30);
OFF(IOSThread, arg, 0x34);
OFF(IOSThread, func, 0x38);
OFF(IOSThread, flags, 0x3C);
OFF(IOSThread, sleeping, 0x40);
OFF(IOSThread, pad44, 0x44);
OFF(IOSThread, hasQueue, 0x48);
OFF(IOSThread, queue, 0x4C);
OFF(IOSThread, name, 0x50);
OFF(IOSThread, pad60, 0x60);
#endif

/* IosSema: runtime, ico2/fumi/include/thread.h:33 */
#if ICO_LAYOUT_EE
OFF(IosSema, param, 0x0);
OFF(IosSema, status, 0x18);
OFF(IosSema, id, 0x30);
#endif

/* WayPoint: runtime, ico2/fumi/include/way_llf.h:20 */
#if ICO_LAYOUT_EE
OFF(WayPoint, used, 0x0);
OFF(WayPoint, index, 0x4);
OFF(WayPoint, prev, 0x8);
OFF(WayPoint, next, 0xC);
OFF(WayPoint, pos, 0x10);
OFF(WayPoint, group, 0x20);
OFF(WayPoint, radius, 0x24);
OFF(WayPoint, escape, 0x28);
OFF(WayPoint, float2C, 0x2C);
OFF(WayPoint, bridgeEnd, 0x30);
OFF(WayPoint, pad34, 0x34);
SIZE(WayPoint, 0x40); /* comment */
#endif

/* WayGroup: runtime, ico2/fumi/include/way_llf.h:36 */
#if ICO_LAYOUT_EE
OFF(WayGroup, used, 0x0);
OFF(WayGroup, index, 0x4);
OFF(WayGroup, first, 0x8);
OFF(WayGroup, last, 0xC);
OFF(WayGroup, count, 0x10);
OFF(WayGroup, closed, 0x14);
OFF(WayGroup, bridge, 0x18);
OFF(WayGroup, boxBridge, 0x1C);
OFF(WayGroup, end, 0x20);
OFF(WayGroup, active, 0x28);
OFF(WayGroup, temp, 0x2C);
OFF(WayGroup, pad30, 0x30);
SIZE(WayGroup, 0x34); /* comment */
#endif

/* WaySrcPt: overlay, ico2/fumi/include/way_tool.h:25 */
OFF(WaySrcPt, pos, 0x0);
OFF(WaySrcPt, radius, 0xC);
OFF(WaySrcPt, escape, 0x10);
OFF(WaySrcPt, float14, 0x14);
OFF(WaySrcPt, bridgeEnd, 0x18);
SIZE(WaySrcPt, 0x1C); /* comment */

/* WaySrcGrp: overlay, ico2/fumi/include/way_tool.h:36 */
OFF(WaySrcGrp, name, 0x0);
OFF(WaySrcGrp, firstPoint, 0x20);
OFF(WaySrcGrp, lastPoint, 0x24);
OFF(WaySrcGrp, closed, 0x28);
OFF(WaySrcGrp, bridge, 0x2C);
OFF(WaySrcGrp, bridgeEnd, 0x30);
OFF(WaySrcGrp, active, 0x38);
SIZE(WaySrcGrp, 0x3C); /* comment */

/* WgAll: runtime, ico2/fumi/include/way_util.h:20 */
#if ICO_LAYOUT_EE
OFF(WgAll, visited, 0x0);
OFF(WgAll, costBuf, 0x4);
OFF(WgAll, cost, 0x8);
OFF(WgAll, prev, 0xC);
OFF(WgAll, prev2, 0x10);
OFF(WgAll, dist, 0x14);
OFF(WgAll, dist2, 0x18);
#endif

/* BirdWork: runtime, ico2/ito/include/act_bird.h:14 */
#if ICO_LAYOUT_EE
OFF(BirdWork, home, 0x0);
OFF(BirdWork, scared, 0x10);
OFF(BirdWork, pad11, 0x11);
OFF(BirdWork, scarer, 0x20);
OFF(BirdWork, bga, 0x30);
OFF(BirdWork, pad34, 0x34);
#endif

/* GObjMailEntry: runtime, ico2/ito/include/itou_common.h:23 */
#if ICO_LAYOUT_EE
OFF(GObjMailEntry, mail, 0x0);
OFF(GObjMailEntry, data, 0x4);
#endif

/* GObjMailQueue: runtime, ico2/ito/include/itou_common.h:28 */
#if ICO_LAYOUT_EE
OFF(GObjMailQueue, pad0, 0x0);
OFF(GObjMailQueue, num, 0x4);
OFF(GObjMailQueue, e, 0x8);
#endif

/* LightningNode: runtime, ico2/ito/include/lightning.h:27 */
#if ICO_LAYOUT_EE
OFF(LightningNode, pos, 0x0);
OFF(LightningNode, key, 0x10);
OFF(LightningNode, pad14, 0x14);
#endif

/* AudioDec: runtime, ico2/ito/include/mv_audiodec.h:18 */
#if ICO_LAYOUT_EE
OFF(AudioDec, state, 0x0);
OFF(AudioDec, id, 0x4);
OFF(AudioDec, headerSize, 0x8);
OFF(AudioDec, type, 0xC);
OFF(AudioDec, sampleRate, 0x10);
OFF(AudioDec, channels, 0x14);
OFF(AudioDec, interleaveSize, 0x18);
OFF(AudioDec, interleaveStart, 0x1C);
OFF(AudioDec, interleaveEnd, 0x20);
OFF(AudioDec, dataId, 0x24);
OFF(AudioDec, dataSize, 0x28);
OFF(AudioDec, headerBytes, 0x2C);
OFF(AudioDec, ring, 0x30);
OFF(AudioDec, writePos, 0x34);
OFF(AudioDec, filled, 0x38);
OFF(AudioDec, ringSize, 0x3C);
OFF(AudioDec, putTotal, 0x40);
OFF(AudioDec, iopBuf, 0x44);
OFF(AudioDec, iopSize, 0x48);
OFF(AudioDec, iopPos, 0x4C);
OFF(AudioDec, word50, 0x50);
OFF(AudioDec, sentTotal, 0x54);
OFF(AudioDec, mono, 0x58);
OFF(AudioDec, pad59, 0x59);
OFF(AudioDec, volume, 0x5C);
OFF(AudioDec, pcmInited, 0x60);
OFF(AudioDec, ch0Open, 0x61);
OFF(AudioDec, ch1Open, 0x62);
OFF(AudioDec, pad63, 0x63);
SIZE(AudioDec, 0x68); /* comment */
#endif

/* MvDispEnv: runtime, ico2/ito/include/mv_disp.h:17 */
#if ICO_LAYOUT_EE
OFF(MvDispEnv, env.w.pmode, 0x0);
OFF(MvDispEnv, env.w.smode2, 0x8);
OFF(MvDispEnv, env.w.dispfb, 0x10);
OFF(MvDispEnv, env.w.dispfbDB, 0x14);
OFF(MvDispEnv, fbp, 0x28);
OFF(MvDispEnv, width, 0x30);
OFF(MvDispEnv, height, 0x34);
OFF(MvDispEnv, imageWidth, 0x38);
OFF(MvDispEnv, imageHeight, 0x3C);
#endif

/* ReadBuf: runtime, ico2/ito/include/mv_readbuf.h:12 */
#if ICO_LAYOUT_EE
OFF(ReadBuf, data, 0x0);
OFF(ReadBuf, size, 0x4);
OFF(ReadBuf, put, 0x8);
OFF(ReadBuf, count, 0xC);
#endif

/* MvCbStr: runtime, ico2/ito/include/mv_readbuf.h:28 */
#if ICO_LAYOUT_EE
OFF(MvCbStr, type, 0x0);
OFF(MvCbStr, pad4, 0x4);
OFF(MvCbStr, data, 0x8);
OFF(MvCbStr, len, 0xC);
OFF(MvCbStr, pts, 0x10);
OFF(MvCbStr, dts, 0x18);
#endif

/* ViBuf: runtime, ico2/ito/include/mv_vibuf.h:16 */
#if ICO_LAYOUT_EE
OFF(ViBuf, data, 0x0);
OFF(ViBuf, dmaTag, 0x4);
OFF(ViBuf, nSector, 0x8);
OFF(ViBuf, rdSector, 0xC);
OFF(ViBuf, nReady, 0x10);
OFF(ViBuf, wOffset, 0x14);
OFF(ViBuf, size, 0x18);
OFF(ViBuf, inMadr, 0x1C);
OFF(ViBuf, inTadr, 0x20);
OFF(ViBuf, inQwc, 0x24);
OFF(ViBuf, inChcr, 0x28);
OFF(ViBuf, outMadr, 0x2C);
OFF(ViBuf, outQwc, 0x30);
OFF(ViBuf, outChcr, 0x34);
OFF(ViBuf, bitPos, 0x38);
OFF(ViBuf, ipuCtrl, 0x3C);
OFF(ViBuf, sema, 0x40);
OFF(ViBuf, running, 0x44);
OFF(ViBuf, total, 0x48);
OFF(ViBuf, ts, 0x50);
OFF(ViBuf, tsMax, 0x54);
OFF(ViBuf, tsCount, 0x58);
OFF(ViBuf, tsWr, 0x5C);
OFF(ViBuf, created, 0x60);
#endif

/* VideoDec: runtime, ico2/ito/include/mv_videodec.h:19 */
#if ICO_LAYOUT_EE
OFF(VideoDec, mpeg, 0x0);
OFF(VideoDec, buf, 0x48);
OFF(VideoDec, vibuf, 0x50);
OFF(VideoDec, state, 0xB8);
OFF(VideoDec, padBC, 0xBC);
OFF(VideoDec, dmacHandler, 0xC0);
OFF(VideoDec, intcHandler, 0xC4);
#endif

/* MvCbErr: runtime, ico2/ito/include/mv_videodec.h:30 */
#if ICO_LAYOUT_EE
OFF(MvCbErr, type, 0x0);
OFF(MvCbErr, message, 0x4);
#endif

/* MvCbTs: runtime, ico2/ito/include/mv_videodec.h:37 */
#if ICO_LAYOUT_EE
OFF(MvCbTs, type, 0x0);
OFF(MvCbTs, pad4, 0x4);
OFF(MvCbTs, pts, 0x8);
OFF(MvCbTs, dts, 0x10);
#endif

/* VoTag: runtime, ico2/ito/include/mv_vobuf.h:13 */
#if ICO_LAYOUT_EE
OFF(VoTag, status, 0x0);
OFF(VoTag, pad4, 0x4);
OFF(VoTag, packet, 0x40);
#endif

/* VoBuf: runtime, ico2/ito/include/mv_vobuf.h:25 */
#if ICO_LAYOUT_EE
OFF(VoBuf, data, 0x0);
OFF(VoBuf, tag, 0x4);
OFF(VoBuf, idx, 0x8);
OFF(VoBuf, count, 0xC);
OFF(VoBuf, max, 0x10);
#endif

/* AttackKindEntry: overlay, ico2/omori/include/attackhit.h:14 */
OFF(AttackKindEntry, word0, 0x0);
OFF(AttackKindEntry, radius, 0x18);
OFF(AttackKindEntry, power, 0x1C);

/* PinRec: overlay, ico2/omori/include/camera-editor.h:21 */
OFF(PinRec, pos, 0x0);
OFF(PinRec, look, 0xC);
OFF(PinRec, ofs, 0x18);
OFF(PinRec, on, 0x24);
OFF(PinRec, fov, 0x28);
OFF(PinRec, word2C, 0x2C);
OFF(PinRec, range, 0x30);
OFF(PinRec, word34, 0x34);
OFF(PinRec, eyeRate, 0x38);
OFF(PinRec, atRate, 0x3C);
OFF(PinRec, limitP, 0x40);
OFF(PinRec, limitV, 0x44);
OFF(PinRec, float48, 0x48);
OFF(PinRec, float4C, 0x4C);
OFF(PinRec, ofsB, 0x50);
SIZE(PinRec, 0x5C); /* comment */

/* CamGroup: overlay, ico2/omori/include/camera-editor.h:44 */
OFF(CamGroup, name, 0x0);
OFF(CamGroup, center, 0x20);
OFF(CamGroup, range, 0x2C);
OFF(CamGroup, first, 0x38);
OFF(CamGroup, end, 0x3C);
OFF(CamGroup, mode, 0x40);
OFF(CamGroup, kind, 0x44);
OFF(CamGroup, items, 0x48);
SIZE(CamGroup, 0x4C); /* comment */

/* CamSetFile: overlay, ico2/omori/include/camera-editor.h:69 */
OFF(CamSetFile, magic, 0x0);
OFF(CamSetFile, ver, 0x4);
OFF(CamSetFile, count, 0x8);
OFF(CamSetFile, total, 0xC);
SIZE(CamSetFile, 0x10); /* config */

/* MenuThread: runtime, ico2/omori/include/camera-editor.h:83 */
#if ICO_LAYOUT_EE
OFF(MenuThread, parent, 0x70);
OFF(MenuThread, arg, 0x74);
#endif

/* EBSlot: runtime, ico2/omori/include/ebrain.h:19 */
#if ICO_LAYOUT_EE
OFF(EBSlot, status, 0x0);
OFF(EBSlot, pad2, 0x2);
OFF(EBSlot, target, 0x4);
OFF(EBSlot, dist, 0x8);
OFF(EBSlot, message, 0x10);
OFF(EBSlot, chaseFrames, 0x14);
OFF(EBSlot, owner, 0x18);
#endif

/* ObjActMailEnt: overlay, ico2/omori/include/objact.h:22 */
OFF(ObjActMailEnt, labelId, 0x0);
OFF(ObjActMailEnt, triggerNo, 0x4);

/* EffectArg: runtime, ico2/script/include/e3.h:47 */
#if ICO_LAYOUT_EE
OFF(EffectArg, d.lo, 0x0);
OFF(EffectArg, d.hi, 0x8);
SIZE(EffectArg, 0x10); /* comment */
#endif

/* WarpRec: overlay, ico2/script/include/script.h:149 */
OFF(WarpRec, arrive2, 0x0);
OFF(WarpRec, arrive1, 0x10);
OFF(WarpRec, arrive0, 0x20);
OFF(WarpRec, gflag, 0x30);
OFF(WarpRec, box0, 0x34);
OFF(WarpRec, box1, 0x40);
OFF(WarpRec, to0, 0x4C);
OFF(WarpRec, to1, 0x4E);
OFF(WarpRec, to2, 0x50);
OFF(WarpRec, from, 0x52);
OFF(WarpRec, kind, 0x54);
OFF(WarpRec, pad55, 0x55);
SIZE(WarpRec, 0x58); /* comment */

/* BgaEnvEnt: overlay, ico2/seki/include/BgAnimation.h:31 */
OFF(BgaEnvEnt, type, 0x0);
OFF(BgaEnvEnt, pad02, 0x2);
OFF(BgaEnvEnt, data, 0x4);
SIZE(BgaEnvEnt, 0x8); /* comment */

/* BgaDObjEnt: overlay, ico2/seki/include/BgAnimation.h:42 */
OFF(BgaDObjEnt, type, 0x0);
OFF(BgaDObjEnt, num, 0x2);
OFF(BgaDObjEnt, name, 0x4);
OFF(BgaDObjEnt, u, 0x24);
OFF(BgaDObjEnt, env, 0x28);
OFF(BgaDObjEnt, child, 0x2C);
OFF(BgaDObjEnt, sibling, 0x30);
OFF(BgaDObjEnt, motion, 0x34);
OFF(BgaDObjEnt, pad38, 0x38);
OFF(BgaDObjEnt, parent, 0x44);
OFF(BgaDObjEnt, pad46, 0x46);
SIZE(BgaDObjEnt, 0x48); /* comment */

/* BgaKey: overlay, ico2/seki/include/BgAnimation.h:63 */
OFF(BgaKey, v, 0x0);
OFF(BgaKey, tension, 0x18);
OFF(BgaKey, bias, 0x1C);
OFF(BgaKey, linear, 0x20);
OFF(BgaKey, time, 0x24);
SIZE(BgaKey, 0x28); /* comment */

/* BgaMotion: overlay, ico2/seki/include/BgAnimation.h:72 */
OFF(BgaMotion, key, 0x0);
OFF(BgaMotion, n, 0x4);
OFF(BgaMotion, len, 0x8);
OFF(BgaMotion, frame, 0xC);

/* BgaPtKey: overlay, ico2/seki/include/BgAnimation.h:83 */
OFF(BgaPtKey, pos, 0x0);
OFF(BgaPtKey, rot, 0xC);
OFF(BgaPtKey, col, 0x18);
OFF(BgaPtKey, tension, 0x24);
OFF(BgaPtKey, bias, 0x28);
OFF(BgaPtKey, linear, 0x2C);
OFF(BgaPtKey, time, 0x30);
SIZE(BgaPtKey, 0x34); /* comment */

/* BgaPtMotion: overlay, ico2/seki/include/BgAnimation.h:94 */
OFF(BgaPtMotion, key, 0x0);
OFF(BgaPtMotion, n, 0x4);
OFF(BgaPtMotion, len, 0x8);
OFF(BgaPtMotion, frame, 0xC);

/* BgaExtKey: overlay, ico2/seki/include/BgAnimation.h:102 */
OFF(BgaExtKey, value, 0x0);
OFF(BgaExtKey, tension, 0x4);
OFF(BgaExtKey, bias, 0x8);
OFF(BgaExtKey, linear, 0xC);
OFF(BgaExtKey, time, 0x10);
SIZE(BgaExtKey, 0x14); /* comment */

/* BgaExtMotion: overlay, ico2/seki/include/BgAnimation.h:111 */
OFF(BgaExtMotion, key, 0x0);
OFF(BgaExtMotion, n, 0x4);
OFF(BgaExtMotion, len, 0x8);
OFF(BgaExtMotion, frame, 0xC);

/* BgaSdfKey: overlay, ico2/seki/include/BgAnimation.h:119 */
OFF(BgaSdfKey, pad00, 0x0);
OFF(BgaSdfKey, pos, 0x4);
OFF(BgaSdfKey, at, 0x10);
OFF(BgaSdfKey, roll, 0x1C);
OFF(BgaSdfKey, fov, 0x20);
SIZE(BgaSdfKey, 0x24); /* comment */

/* BgaSdfCam: overlay, ico2/seki/include/BgAnimation.h:130 */
OFF(BgaSdfCam, id, 0x0);
OFF(BgaSdfCam, num, 0x4);
OFF(BgaSdfCam, frame, 0x8);
OFF(BgaSdfCam, mode, 0xC);
OFF(BgaSdfCam, key, 0x10);

/* BgaAnim: runtime, ico2/seki/include/BgAnimation.h:141 */
#if ICO_LAYOUT_EE
OFF(BgaAnim, pos, 0x0);
OFF(BgaAnim, quat, 0x10);
OFF(BgaAnim, obj, 0x20);
OFF(BgaAnim, idx, 0x24);
OFF(BgaAnim, root, 0x28);
OFF(BgaAnim, pad2C, 0x2C);
SIZE(BgaAnim, 0x30); /* comment */
#endif

/* BgaHeader: overlay, ico2/seki/include/BgAnimation.h:155 */
OFF(BgaHeader, group, 0x4);
OFF(BgaHeader, pad8, 0x8);
OFF(BgaHeader, mode, 0xA);
OFF(BgaHeader, cut, 0xB);
OFF(BgaHeader, dobjs, 0xC);
OFF(BgaHeader, roots, 0x10);
OFF(BgaHeader, start, 0x14);
OFF(BgaHeader, end, 0x18);
OFF(BgaHeader, step, 0x1C);
OFF(BgaHeader, frame, 0x20);
OFF(BgaHeader, anim, 0x24);

/* PObjMorph: overlay, ico2/seki/include/DisplayP2O.h:21 */
OFF(PObjMorph, delta, 0x0);
OFF(PObjMorph, isVertex, 0xC);
OFF(PObjMorph, index, 0x10);
OFF(PObjMorph, pad14, 0x14);
SIZE(PObjMorph, 0x20); /* comment */

/* PObjMatDef: overlay, ico2/seki/include/DisplayP2O.h:31 */
OFF(PObjMatDef, pad00, 0x0);
OFF(PObjMatDef, wrap, 0x5);
OFF(PObjMatDef, fbaOff, 0x6);
OFF(PObjMatDef, pad07, 0x7);
OFF(PObjMatDef, alpha, 0xC);
SIZE(PObjMatDef, 0x10); /* comment */

/* PObjTexDef: overlay, ico2/seki/include/DisplayP2O.h:41 */
OFF(PObjTexDef, name, 0x0);
OFF(PObjTexDef, scaleU, 0x84);
OFF(PObjTexDef, scaleV, 0x88);
OFF(PObjTexDef, pad8C, 0x8C);
SIZE(PObjTexDef, 0x90); /* comment */

/* PObjPart: runtime, ico2/seki/include/DisplayP2O.h:55 */
#if ICO_LAYOUT_EE
OFF(PObjPart, pad00, 0x0);
OFF(PObjPart, vtx, 0x90);
OFF(PObjPart, vtxCount, 0x94);
OFF(PObjPart, pad98, 0x98);
OFF(PObjPart, nrm, 0xA0);
OFF(PObjPart, nrmCount, 0xA4);
OFF(PObjPart, padA8, 0xA8);
OFF(PObjPart, uv, 0xB0);
OFF(PObjPart, padB4, 0xB4);
OFF(PObjPart, col, 0xC0);
OFF(PObjPart, padC4, 0xC4);
OFF(PObjPart, mats, 0xD0);
OFF(PObjPart, matCount, 0xD4);
OFF(PObjPart, padD8, 0xD8);
OFF(PObjPart, texDefs, 0xE0);
OFF(PObjPart, texCount, 0xE4);
OFF(PObjPart, padE8, 0xE8);
OFF(PObjPart, polys, 0xF0);
OFF(PObjPart, polyCount, 0xF4);
OFF(PObjPart, padF8, 0xF8);
OFF(PObjPart, strips, 0x100);
OFF(PObjPart, stripCount, 0x104);
OFF(PObjPart, pad108, 0x108);
OFF(PObjPart, lines, 0x110);
OFF(PObjPart, lineCount, 0x114);
OFF(PObjPart, pad118, 0x118);
OFF(PObjPart, morphs, 0x120);
OFF(PObjPart, morphCount, 0x124);
OFF(PObjPart, pad128, 0x128);
OFF(PObjPart, mtx, 0x130);
OFF(PObjPart, pad170, 0x170);
OFF(PObjPart, vtxSave, 0x174);
OFF(PObjPart, nrmSave, 0x178);
OFF(PObjPart, pad17C, 0x17C);
SIZE(PObjPart, 0x180); /* comment */
#endif

/* ObjHdr: overlay, ico2/seki/include/DisplayP2O.h:98 */
OFF(ObjHdr, pad0, 0x0);
OFF(ObjHdr, objTbl, 0x4);
OFF(ObjHdr, objNum, 0x8);
OFF(ObjHdr, clstNum, 0xC);
OFF(ObjHdr, texTbl, 0x10);
OFF(ObjHdr, texNum, 0x14);
SIZE(ObjHdr, 0x18); /* config */

/* ObjEnt: overlay, ico2/seki/include/DisplayP2O.h:110 */
OFF(ObjEnt, p, 0x0);
OFF(ObjEnt, pad4, 0x4);
SIZE(ObjEnt, 0x10); /* comment */

/* ObjRec: overlay, ico2/seki/include/DisplayP2O.h:121 */
OFF(ObjRec, pad0, 0x0);
OFF(ObjRec, magic, 0x80);
OFF(ObjRec, pad84, 0x84);
OFF(ObjRec, vtx, 0x90);
OFF(ObjRec, vtxCount, 0x94);
OFF(ObjRec, pad98, 0x98);
OFF(ObjRec, nrm, 0xA0);
OFF(ObjRec, nrmCount, 0xA4);
OFF(ObjRec, padA8, 0xA8);
OFF(ObjRec, uv, 0xB0);
OFF(ObjRec, padB4, 0xB4);
OFF(ObjRec, col, 0xC0);
OFF(ObjRec, padC4, 0xC4);
OFF(ObjRec, mats, 0xD0);
OFF(ObjRec, matCount, 0xD4);
OFF(ObjRec, padD8, 0xD8);
OFF(ObjRec, texDefs, 0xE0);
OFF(ObjRec, texCount, 0xE4);
OFF(ObjRec, padE8, 0xE8);
OFF(ObjRec, polys, 0xF0);
OFF(ObjRec, polyCount, 0xF4);
OFF(ObjRec, padF8, 0xF8);
OFF(ObjRec, strips, 0x100);
OFF(ObjRec, stripCount, 0x104);
OFF(ObjRec, pad108, 0x108);
OFF(ObjRec, lines, 0x110);
OFF(ObjRec, lineCount, 0x114);
OFF(ObjRec, pad118, 0x118);
OFF(ObjRec, morphs, 0x120);
OFF(ObjRec, morphCount, 0x124);
OFF(ObjRec, pad128, 0x128);
OFF(ObjRec, mtx, 0x130);
OFF(ObjRec, pad170, 0x170);
OFF(ObjRec, vtxSave, 0x174);
OFF(ObjRec, nrmSave, 0x178);
OFF(ObjRec, pad17C, 0x17C);
SIZE(ObjRec, 0x180); /* comment */

/* PObjMaterial: runtime, ico2/seki/include/DisplayP2O.h:166 */
#if ICO_LAYOUT_EE
OFF(PObjMaterial, packet, 0x0);
OFF(PObjMaterial, attr, 0x60);
OFF(PObjMaterial, pad68, 0x68);
SIZE(PObjMaterial, 0x70); /* comment */
#endif

/* PObjTexInfo: runtime, ico2/seki/include/DisplayP2O.h:191 */
#if ICO_LAYOUT_EE
OFF(PObjTexInfo, name, 0x0);
OFF(PObjTexInfo, nameL, 0x18);
OFF(PObjTexInfo, nameRef, 0x30);
OFF(PObjTexInfo, tex, 0x48);
OFF(PObjTexInfo, texL, 0x4A);
OFF(PObjTexInfo, texRef, 0x4C);
OFF(PObjTexInfo, found, 0x4E);
SIZE(PObjTexInfo, 0x50); /* comment */
#endif

/* PObjGroup: runtime, ico2/seki/include/DisplayP2O.h:205 */
#if ICO_LAYOUT_EE
OFF(PObjGroup, materials, 0x0);
OFF(PObjGroup, texs, 0x4);
OFF(PObjGroup, packets, 0x8);
OFF(PObjGroup, morph, 0xC);
OFF(PObjGroup, matCount, 0x10);
OFF(PObjGroup, texCount, 0x12);
OFF(PObjGroup, name, 0x14);
SIZE(PObjGroup, 0x30); /* comment */
#endif

/* PObjModel: runtime, ico2/seki/include/DisplayP2O.h:215 */
#if ICO_LAYOUT_EE
OFF(PObjModel, name, 0x0);
OFF(PObjModel, serial, 0x20);
OFF(PObjModel, pad24, 0x24);
OFF(PObjModel, dobj, 0x28);
OFF(PObjModel, pad2C, 0x2C);
OFF(PObjModel, partCount, 0x2E);
OFF(PObjModel, disp, 0x2F);
OFF(PObjModel, mode, 0x30);
OFF(PObjModel, mode.s.lightScale, 0x34);
OFF(PObjModel, ambientScale, 0x38);
OFF(PObjModel, shadowLength, 0x3C);
OFF(PObjModel, parts, 0x40);
OFF(PObjModel, boxes, 0x44);
OFF(PObjModel, groups, 0x48);
OFF(PObjModel, pad4C, 0x4C);
OFF(PObjModel, box, 0x50);
#endif

/* LightMatrix: runtime, ico2/seki/include/Light.h:24 */
#if ICO_LAYOUT_EE
OFF(LightMatrix, normal, 0x0);
OFF(LightMatrix, color, 0x40);
OFF(LightMatrix, dir, 0x80);
OFF(LightMatrix, col, 0xB0);
OFF(LightMatrix, ambient, 0xE0);
OFF(LightMatrix, mode, 0xF0);
#endif

/* ObjLight: overlay, ico2/seki/include/Light.h:35 */
OFF(ObjLight, col, 0x0);
OFF(ObjLight, range, 0xC);
SIZE(ObjLight, 0x10); /* comment */

/* PacHeader: runtime, ico2/seki/include/Packet.h:19 */
#if ICO_LAYOUT_EE
OFF(PacHeader, box, 0x0);
OFF(PacHeader, mat, 0x80);
OFF(PacHeader, texSlot, 0x82);
OFF(PacHeader, tex, 0x84);
OFF(PacHeader, tex1, 0x86);
OFF(PacHeader, tex2, 0x88);
OFF(PacHeader, ntag, 0x8A);
OFF(PacHeader, npoly, 0x8C);
OFF(PacHeader, clip, 0x93);
OFF(PacHeader, next, 0x94);
OFF(PacHeader, data, 0x98);
OFF(PacHeader, pad9C, 0x9C);
SIZE(PacHeader, 0xA0); /* comment */
#endif

/* PacLine: runtime, ico2/seki/include/Packet.h:49 */
#if ICO_LAYOUT_EE
OFF(PacLine, pos, 0x0);
OFF(PacLine, scrPrev, 0x20);
OFF(PacLine, uv, 0x30);
OFF(PacLine, trail, 0x50);
OFF(PacLine, trailPrev, 0x80);
OFF(PacLine, col0, 0xB0);
OFF(PacLine, col1, 0xB4);
OFF(PacLine, attr, 0xB8);
SIZE(PacLine, 0xC0); /* comment */
#endif

/* PacLineSet: runtime, ico2/seki/include/Packet.h:71 */
#if ICO_LAYOUT_EE
OFF(PacLineSet, pad00, 0x0);
OFF(PacLineSet, lines, 0xC);
OFF(PacLineSet, pad10, 0x10);
SIZE(PacLineSet, 0x90); /* comment */
#endif

/* Mesh3D: runtime, ico2/seki/include/Primitive.h:22 */
#if ICO_LAYOUT_EE
OFF(Mesh3D, nx, 0x0);
OFF(Mesh3D, ny, 0x4);
OFF(Mesh3D, mtx, 0x10);
OFF(Mesh3D, pad5C, 0x5C);
OFF(Mesh3D, col, 0x68);
OFF(Mesh3D, pos, 0x6C);
OFF(Mesh3D, nrm, 0x70);
OFF(Mesh3D, st, 0x74);
OFF(Mesh3D, bufs, 0x7C);
OFF(Mesh3D, pad84, 0x84);
SIZE(Mesh3D, 0x90); /* comment */
#endif

/* Fan2DVtx: runtime, ico2/seki/include/Primitive.h:43 */
#if ICO_LAYOUT_EE
OFF(Fan2DVtx, cr, 0x0);
OFF(Fan2DVtx, cg, 0x4);
OFF(Fan2DVtx, cb, 0x8);
OFF(Fan2DVtx, ca, 0xC);
OFF(Fan2DVtx, x, 0x10);
OFF(Fan2DVtx, y, 0x14);
OFF(Fan2DVtx, z, 0x18);
OFF(Fan2DVtx, w, 0x1C);
#endif

/* Fan2D: runtime, ico2/seki/include/Primitive.h:54 */
#if ICO_LAYOUT_EE
OFF(Fan2D, n, 0x0);
OFF(Fan2D, buf, 0x8);
SIZE(Fan2D, 0xC); /* config */
#endif

/* PrimParticleBuf: runtime, ico2/seki/include/Primitive.h:62 */
#if ICO_LAYOUT_EE
OFF(PrimParticleBuf, head, 0x0);
OFF(PrimParticleBuf, mtx, 0x10);
OFF(PrimParticleBuf, lmtx, 0x50);
OFF(PrimParticleBuf, tail, 0x90);
#endif

/* PrimParticleObj: runtime, ico2/seki/include/Primitive.h:73 */
#if ICO_LAYOUT_EE
OFF(PrimParticleObj, vif, 0x0);
OFF(PrimParticleObj, num, 0x10);
OFF(PrimParticleObj, tag, 0x20);
OFF(PrimParticleObj, clipMin, 0x40);
OFF(PrimParticleObj, clipMax, 0x50);
OFF(PrimParticleObj, pos, 0x60);
OFF(PrimParticleObj, vtx, 0x70);
#endif

/* PrimParticle: runtime, ico2/seki/include/Primitive.h:83 */
#if ICO_LAYOUT_EE
OFF(PrimParticle, buf, 0x0);
OFF(PrimParticle, word144, 0x144);
OFF(PrimParticle, num, 0x148);
OFF(PrimParticle, x, 0x14C);
OFF(PrimParticle, y, 0x150);
OFF(PrimParticle, z, 0x154);
OFF(PrimParticle, name, 0x15C);
OFF(PrimParticle, tex, 0x17C);
OFF(PrimParticle, cur, 0x180);
OFF(PrimParticle, objs, 0x188);
#endif

/* StageAnimDef: overlay, ico2/seki/include/StageAnimation.h:15, 64-bit pending 5 */
#if ICO_LAYOUT_EE || ICO_LAYOUT_PENDING
OFF(StageAnimDef, path, 0x0);
OFF(StageAnimDef, objFirst, 0x40);
OFF(StageAnimDef, objLast, 0x44);
OFF(StageAnimDef, group, 0x48);
OFF(StageAnimDef, cut, 0x4C);
OFF(StageAnimDef, pad4D, 0x4D);
OFF(StageAnimDef, loop, 0x50);
OFF(StageAnimDef, data, 0x54);
OFF(StageAnimDef, no, 0x58);
SIZE(StageAnimDef, 0x5C); /* comment */
#endif

/* StgObjDat: overlay, ico2/seki/include/StageAnimation.h:30 */
OFF(StgObjDat, kind, 0x0);
OFF(StgObjDat, aux, 0x4);
SIZE(StgObjDat, 0x8); /* comment */

/* BgaPlayNode: runtime, ico2/seki/include/StageAnimation.h:40 */
#if ICO_LAYOUT_EE
OFF(BgaPlayNode, num, 0x2);
OFF(BgaPlayNode, frame, 0x4);
OFF(BgaPlayNode, speed, 0x8);
OFF(BgaPlayNode, scale, 0xC);
OFF(BgaPlayNode, prev, 0x10);
OFF(BgaPlayNode, next, 0x14);
OFF(BgaPlayNode, pad18, 0x18);
OFF(BgaPlayNode, pos, 0x20);
OFF(BgaPlayNode, rot, 0x30);
#endif

/* Tim2Picture: overlay, ico2/seki/include/Tim2.h:24 */
OFF(Tim2Picture, totalSize, 0x0);
OFF(Tim2Picture, clutSize, 0x4);
OFF(Tim2Picture, imageSize, 0x8);
OFF(Tim2Picture, headerSize, 0xC);
OFF(Tim2Picture, clutColors, 0xE);
OFF(Tim2Picture, picFormat, 0x10);
OFF(Tim2Picture, mipMapTextures, 0x11);
OFF(Tim2Picture, clutType, 0x12);
OFF(Tim2Picture, imageType, 0x13);
OFF(Tim2Picture, imageWidth, 0x14);
OFF(Tim2Picture, imageHeight, 0x16);
OFF(Tim2Picture, GsTex0, 0x18);
OFF(Tim2Picture, GsTex1, 0x20);
OFF(Tim2Picture, GsRegs, 0x28);
OFF(Tim2Picture, GsTexClut, 0x2C);
SIZE(Tim2Picture, 0x30); /* config */

/* Tim2Mipmap: overlay, ico2/seki/include/Tim2.h:48 */
OFF(Tim2Mipmap, GsMiptbp1, 0x0);
OFF(Tim2Mipmap, GsMiptbp2, 0x8);
OFF(Tim2Mipmap, sizes, 0x10);
SIZE(Tim2Mipmap, 0x30); /* config */

/* LayoutClothDef: overlay, ico2/sugipon/include/attackCheckBoundary.h:36 */
OFF(LayoutClothDef, name, 0x0);
OFF(LayoutClothDef, pt, 0x20);
OFF(LayoutClothDef, kind, 0x50);
OFF(LayoutClothDef, attr, 0x54);
OFF(LayoutClothDef, rows, 0x58);
OFF(LayoutClothDef, count, 0x5C);
OFF(LayoutClothDef, length, 0x60);
OFF(LayoutClothDef, weight, 0x64);

/* AccessaryRec: overlay, ico2/sugipon/include/box.h:15 */
OFF(AccessaryRec, model, 0x0);
OFF(AccessaryRec, model2, 0x4);
OFF(AccessaryRec, subModel, 0x8);
OFF(AccessaryRec, pivot, 0xC);
OFF(AccessaryRec, subPos, 0x18);
OFF(AccessaryRec, subRotY, 0x24);
SIZE(AccessaryRec, 0x28); /* comment */

/* MotSyncPair: overlay, ico2/sugipon/include/boy.h:16 */
OFF(MotSyncPair, girl, 0x0);
OFF(MotSyncPair, boy, 0x4);
SIZE(MotSyncPair, 0x8); /* comment */

/* ClipColReq: runtime, ico2/sugipon/include/clipCollisionManager.h:20 */
#if ICO_LAYOUT_EE
OFF(ClipColReq, done, 0x0);
OFF(ClipColReq, pad04, 0x4);
OFF(ClipColReq, clip, 0x10);
OFF(ClipColReq, obj, 0xD0);
OFF(ClipColReq, func, 0xD4);
#endif

/* ExW: runtime, ico2/sugipon/include/clothAnimation.h:21 */
#if ICO_LAYOUT_EE
OFF(ExW, len0, 0x40);
OFF(ExW, len1, 0x44);
OFF(ExW, pad48, 0x48);
#endif

/* ChainNode: runtime, ico2/sugipon/include/clothAnimation.h:33 */
#if ICO_LAYOUT_EE
OFF(ChainNode, pos, 0x0);
OFF(ChainNode, vel, 0x4);
OFF(ChainNode, len, 0x8);
OFF(ChainNode, exNum, 0xC);
SIZE(ChainNode, 0x1A0); /* comment */
#endif

/* ChainParam: runtime, ico2/sugipon/include/clothAnimation.h:44 */
#if ICO_LAYOUT_EE
OFF(ChainParam, node, 0x0);
OFF(ChainParam, step, 0x4);
OFF(ChainParam, pad08, 0x8);
OFF(ChainParam, root, 0x10);
OFF(ChainParam, pad20, 0x20);
OFF(ChainParam, weight, 0x30);
OFF(ChainParam, pad34, 0x34);
#endif

/* ClothCfg: runtime, ico2/sugipon/include/clothAnimation.h:73 */
#if ICO_LAYOUT_EE
OFF(ClothCfg, num, 0x0);
OFF(ClothCfg, segLength, 0x4);
OFF(ClothCfg, div, 0x8);
OFF(ClothCfg, wrap, 0xC);
OFF(ClothCfg, anchors, 0x10);
OFF(ClothCfg, tex, 0x14);
OFF(ClothCfg, weight, 0x18);
SIZE(ClothCfg, 0x1C); /* comment */
#endif

/* ClothRec: runtime, ico2/sugipon/include/clothAnimation.h:91 */
#if ICO_LAYOUT_EE
OFF(ClothRec, mesh, 0x0);
OFF(ClothRec, pos, 0x4);
OFF(ClothRec, vel, 0x8);
OFF(ClothRec, mark, 0xC);
OFF(ClothRec, textured, 0x10);
OFF(ClothRec, pad14, 0x14);
OFF(ClothRec, tex, 0x18);
SIZE(ClothRec, 0x2E0); /* comment */
#endif

/* ClothHangCfg: runtime, ico2/sugipon/include/clothAnimation.h:135 */
#if ICO_LAYOUT_EE
OFF(ClothHangCfg, enable, 0x0);
OFF(ClothHangCfg, bottom, 0x4);
OFF(ClothHangCfg, top, 0x8);
OFF(ClothHangCfg, radius, 0xC);
OFF(ClothHangCfg, node, 0x10);
OFF(ClothHangCfg, pad14, 0x14);
OFF(ClothHangCfg, posX, 0x20);
OFF(ClothHangCfg, posY, 0x24);
OFF(ClothHangCfg, pad28, 0x28);
OFF(ClothHangCfg, posW, 0x2C);
OFF(ClothHangCfg, turn, 0x30);
OFF(ClothHangCfg, pad34, 0x34);
#endif

/* Cloth4DCol: runtime, ico2/sugipon/include/clothAnimation.h:161 */
#if ICO_LAYOUT_EE
OFF(Cloth4DCol, length, 0x0);
OFF(Cloth4DCol, pad04, 0x4);
OFF(Cloth4DCol, pos, 0x10);
OFF(Cloth4DCol, dir, 0x20);
OFF(Cloth4DCol, link, 0x30);
OFF(Cloth4DCol, uv, 0x40);
OFF(Cloth4DCol, pad44, 0x44);
OFF(Cloth4DCol, restDir, 0x50);
#endif

/* Cloth4DCfg: runtime, ico2/sugipon/include/clothAnimation.h:177 */
#if ICO_LAYOUT_EE
OFF(Cloth4DCfg, wrap, 0x8);
OFF(Cloth4DCfg, word0C, 0xC);
OFF(Cloth4DCfg, r, 0x10);
OFF(Cloth4DCfg, g, 0x14);
OFF(Cloth4DCfg, b, 0x18);
OFF(Cloth4DCfg, a, 0x1C);
OFF(Cloth4DCfg, colSpacing, 0x28);
OFF(Cloth4DCfg, word2C, 0x2C);
#endif

/* ClothPoint: runtime, ico2/sugipon/include/clothAnimation.h:195 */
#if ICO_LAYOUT_EE
OFF(ClothPoint, bottom, 0x4);
OFF(ClothPoint, pad10, 0x10);
OFF(ClothPoint, pos, 0x20);
OFF(ClothPoint, turn, 0x30);
OFF(ClothPoint, invDiameter, 0x34);
OFF(ClothPoint, pad38, 0x38);
#endif

/* struct Cloth4D: runtime, ico2/sugipon/include/clothAnimation.h:209 */
#if ICO_LAYOUT_EE
OFF(struct Cloth4D, pos, 0x8);
OFF(struct Cloth4D, vel, 0xC);
OFF(struct Cloth4D, nrm, 0x10);
OFF(struct Cloth4D, pad14, 0x14);
OFF(struct Cloth4D, colNum, 0x2E4);
OFF(struct Cloth4D, colNode, 0x2E8);
OFF(struct Cloth4D, colMtx, 0x2EC);
OFF(struct Cloth4D, col, 0x2F0);
OFF(struct Cloth4D, sweepRight, 0x2F4);
OFF(struct Cloth4D, collision, 0x2F8);
SIZE(struct Cloth4D, 0x300); /* config */
#endif

/* EnemyKindRange: overlay, ico2/sugipon/include/enemy.h:16 */
OFF(EnemyKindRange, first, 0x0);
OFF(EnemyKindRange, last, 0x4);
SIZE(EnemyKindRange, 0x8); /* comment */

/* EnemyDef: overlay, ico2/sugipon/include/enemy.h:25 */
OFF(EnemyDef, model, 0x0);
OFF(EnemyDef, particle, 0x4);
OFF(EnemyDef, life, 0x8);
OFF(EnemyDef, float0C, 0xC);
OFF(EnemyDef, scale, 0x10);
OFF(EnemyDef, dodge, 0x14);
SIZE(EnemyDef, 0x1C); /* comment */

/* EnemyEye: runtime, ico2/sugipon/include/enemyParts.h:14 */
#if ICO_LAYOUT_EE
OFF(EnemyEye, blurOn, 0x0);
OFF(EnemyEye, blur, 0x4);
OFF(EnemyEye, pad8, 0x8);
OFF(EnemyEye, mtx, 0x10);
OFF(EnemyEye, dobj, 0x50);
OFF(EnemyEye, pad5C, 0x5C);
SIZE(EnemyEye, 0x60); /* comment */
#endif

/* EnemyFootPrint: runtime, ico2/sugipon/include/enemyParts.h:25 */
#if ICO_LAYOUT_EE
OFF(EnemyFootPrint, life, 0x0);
OFF(EnemyFootPrint, speed, 0x4);
OFF(EnemyFootPrint, pad8, 0x8);
OFF(EnemyFootPrint, pos, 0x10);
#endif

/* EnemyFootPrintHead: runtime, ico2/sugipon/include/enemyParts.h:32 */
#if ICO_LAYOUT_EE
OFF(EnemyFootPrintHead, num, 0x0);
OFF(EnemyFootPrintHead, dobj, 0x4);
OFF(EnemyFootPrintHead, idx, 0x8);
OFF(EnemyFootPrintHead, buf, 0xC);
#endif

/* SePackage: overlay, ico2/sugipon/include/frameDependSequence.h:14 */
OFF(SePackage, se, 0x0);
OFF(SePackage, id, 0x8);
SIZE(SePackage, 0xC); /* comment */

/* SERandEntry: overlay, ico2/sugipon/include/frameDependSequence.h:21 */
OFF(SERandEntry, se, 0x0);
OFF(SERandEntry, rate, 0x4);
SIZE(SERandEntry, 0x8); /* comment */

/* SECondEntry: overlay, ico2/sugipon/include/frameDependSequence.h:27 */
OFF(SECondEntry, kind, 0x0);
OFF(SECondEntry, cond, 0x4);
OFF(SECondEntry, se, 0x8);
SIZE(SECondEntry, 0xC); /* comment */

/* EffEntry: overlay, ico2/sugipon/include/frameDependSequence.h:36 */
OFF(EffEntry, x, 0x0);
OFF(EffEntry, y, 0x4);
OFF(EffEntry, z, 0x8);
OFF(EffEntry, rx, 0xC);
OFF(EffEntry, ry, 0x10);
OFF(EffEntry, rz, 0x14);
OFF(EffEntry, eff, 0x18);
OFF(EffEntry, node, 0x1C);
OFF(EffEntry, flags, 0x20);
SIZE(EffEntry, 0x24); /* comment */

/* VibCondEntry: overlay, ico2/sugipon/include/frameDependSequence.h:51 */
OFF(VibCondEntry, kind, 0x0);
OFF(VibCondEntry, cond, 0x4);
OFF(VibCondEntry, actId, 0x8);
SIZE(VibCondEntry, 0xC); /* comment */

/* HandModeRow: overlay, ico2/sugipon/include/handManager.h:14 */
OFF(HandModeRow, dir, 0x0);
OFF(HandModeRow, mode, 0xC);
SIZE(HandModeRow, 0x10); /* comment */

/* ItemBreakRec: overlay, ico2/sugipon/include/item.h:17 */
OFF(ItemBreakRec, stayAnim, 0x0);
OFF(ItemBreakRec, stayMode, 0x4);
OFF(ItemBreakRec, breakAnim, 0x8);
OFF(ItemBreakRec, breakMode, 0xC);
OFF(ItemBreakRec, dropAnim, 0x10);
OFF(ItemBreakRec, hitAnim, 0x14);
OFF(ItemBreakRec, hitMode, 0x18);
OFF(ItemBreakRec, flags, 0x1C);
SIZE(ItemBreakRec, 0x20); /* comment */

/* NodeRec: overlay, ico2/sugipon/include/motionFileManager.h:32 */
OFF(NodeRec, nTable, 0x0);
OFF(NodeRec, lastTable, 0x4);

/* FacialRec: overlay, ico2/sugipon/include/motionFileManager.h:39 */
OFF(FacialRec, count, 0x0);
OFF(FacialRec, tbl, 0x4);

/* MotFileHdr: overlay, ico2/sugipon/include/motionFileManager.h:48 */
OFF(MotFileHdr, frames, 0x0);
OFF(MotFileHdr, rootPos, 0x4);
OFF(MotFileHdr, typeList, 0x8);
OFF(MotFileHdr, nodeList, 0xC);
OFF(MotFileHdr, facial, 0x10);

/* MotionOrientEntry: overlay, ico2/sugipon/include/motionOrientManager.h:16 */
OFF(MotionOrientEntry, id, 0x0);
OFF(MotionOrientEntry, kind, 0x4);
OFF(MotionOrientEntry, nextId, 0x8);
OFF(MotionOrientEntry, shiftFrom, 0xC);
OFF(MotionOrientEntry, shiftMode, 0x10);
OFF(MotionOrientEntry, word14, 0x14);
SIZE(MotionOrientEntry, 0x18); /* comment */

/* MotOriParallelEnt: overlay, ico2/sugipon/include/motionOrientManager.h:27 */
OFF(MotOriParallelEnt, id, 0x0);
OFF(MotOriParallelEnt, kind, 0x4);
OFF(MotOriParallelEnt, nextId, 0x8);
OFF(MotOriParallelEnt, shiftFrom, 0xC);
OFF(MotOriParallelEnt, shiftMode, 0x10);
SIZE(MotOriParallelEnt, 0x14); /* comment */

/* MotOriAlt: overlay, ico2/sugipon/include/motionOrientManager.h:37 */
OFF(MotOriAlt, req, 0x0);
OFF(MotOriAlt, alt, 0x4);
SIZE(MotOriAlt, 0x8); /* comment */

/* MotOriName: overlay, ico2/sugipon/include/motionOrientManager.h:45 */
OFF(MotOriName, s, 0x0);
SIZE(MotOriName, 0x20); /* comment */

/* MotOriSub: overlay, ico2/sugipon/include/motionOrientManager.h:51 */
OFF(MotOriSub, motion, 0x0);
OFF(MotOriSub, node, 0x4);
OFF(MotOriSub, rate, 0x8);
OFF(MotOriSub, frames, 0xC);
SIZE(MotOriSub, 0x10); /* comment */

/* MotOriLimit: overlay, ico2/sugipon/include/motionOrientManager.h:66 */
OFF(MotOriLimit, lo, 0x0);
OFF(MotOriLimit, mid, 0xC);
OFF(MotOriLimit, hi, 0x18);
OFF(MotOriLimit, node, 0x24);
OFF(MotOriLimit, float28, 0x28);
OFF(MotOriLimit, word2C, 0x2C);
SIZE(MotOriLimit, 0x30); /* comment */

/* FDSSlot: overlay, ico2/sugipon/include/motionOrientManager.h:76 */
OFF(FDSSlot, t, 0x0);
OFF(FDSSlot, no, 0x4);

/* MotionDef: overlay, ico2/sugipon/include/motionOrientManager.h:141 */
OFF(MotionDef, eff, 0x0);
OFF(MotionDef, se, 0x60);
OFF(MotionDef, name, 0xC0);
OFF(MotionDef, vib, 0xF0);
OFF(MotionDef, word100, 0x100);
OFF(MotionDef, cylinder, 0x104);
OFF(MotionDef, adjustAngle, 0x108);
OFF(MotionDef, slopeIK, 0x10C);
OFF(MotionDef, gravity, 0x110);
OFF(MotionDef, noStepSearch, 0x114);
OFF(MotionDef, rootUpdateMode, 0x118);
OFF(MotionDef, stepNode, 0x11C);
OFF(MotionDef, landFrame, 0x120);
OFF(MotionDef, rootOffset, 0x124);
OFF(MotionDef, wallFeedback, 0x130);
OFF(MotionDef, area, 0x134);
OFF(MotionDef, weaponFrame, 0x138);
OFF(MotionDef, shiftStart, 0x13C);
OFF(MotionDef, shiftLength, 0x140);
OFF(MotionDef, triggerStart, 0x144);
OFF(MotionDef, triggerEnd, 0x148);
OFF(MotionDef, trigger2Start, 0x14C);
OFF(MotionDef, playMode, 0x150);
OFF(MotionDef, trigger2End, 0x154);
OFF(MotionDef, faceRotRatio, 0x158);
OFF(MotionDef, palSpeedRatio, 0x15C);
OFF(MotionDef, rate0, 0x160);
OFF(MotionDef, clipRadius, 0x164);
OFF(MotionDef, rate1, 0x168);
OFF(MotionDef, fieldWall, 0x16C);
OFF(MotionDef, lookIK, 0x170);
OFF(MotionDef, playSpeedRatio, 0x174);
OFF(MotionDef, blendKind, 0x178);
OFF(MotionDef, handTurnIK, 0x17C);
OFF(MotionDef, priInputBegin, 0x180);
OFF(MotionDef, girlDirFrames, 0x182);
OFF(MotionDef, priInputEnd, 0x184);
OFF(MotionDef, dirFrames, 0x186);
OFF(MotionDef, modeBits, 0x188);
OFF(MotionDef, flags, 0x18C);
OFF(MotionDef, flags2, 0x190);
SIZE(MotionDef, 0x194); /* comment */

/* BgaDisp: runtime, ico2/sugipon/include/multiBgaManager.h:16 */
#if ICO_LAYOUT_EE
OFF(BgaDisp, frame, 0x0);
OFF(BgaDisp, pad04, 0x4);
OFF(BgaDisp, pos, 0x10);
OFF(BgaDisp, vel, 0x20);
OFF(BgaDisp, rot, 0x30);
OFF(BgaDisp, kind, 0x40);
OFF(BgaDisp, stay, 0x44);
OFF(BgaDisp, pad48, 0x48);
#endif

/* BgaAnimeState: runtime, ico2/sugipon/include/multiBgaManager.h:40 */
#if ICO_LAYOUT_EE
OFF(BgaAnimeState, frame, 0x0);
OFF(BgaAnimeState, pad04, 0x4);
OFF(BgaAnimeState, pos, 0x10);
OFF(BgaAnimeState, vel, 0x20);
OFF(BgaAnimeState, rot, 0x30);
OFF(BgaAnimeState, kind, 0x40);
OFF(BgaAnimeState, stay, 0x44);
OFF(BgaAnimeState, pad48, 0x48);
#endif

/* PEPackage: overlay, ico2/sugipon/include/particleEffect.h:19 */
OFF(PEPackage, version, 0x0);
OFF(PEPackage, mode, 0x4);
OFF(PEPackage, alphaMode, 0x8);
OFF(PEPackage, spread, 0xC);
OFF(PEPackage, pad0E, 0xE);
OFF(PEPackage, speed, 0x10);
OFF(PEPackage, speedRand, 0x14);
OFF(PEPackage, drag, 0x18);
OFF(PEPackage, gravity, 0x1C);
OFF(PEPackage, spinY, 0x20);
OFF(PEPackage, pad22, 0x22);
OFF(PEPackage, spinYRand, 0x24);
OFF(PEPackage, spinYDecay, 0x28);
OFF(PEPackage, size, 0x2C);
OFF(PEPackage, sizeRand, 0x30);
OFF(PEPackage, sizeStep, 0x34);
OFF(PEPackage, sizeStepRand, 0x38);
OFF(PEPackage, sizeStepDecay, 0x3C);
OFF(PEPackage, count, 0x40);
OFF(PEPackage, emit, 0x44);
OFF(PEPackage, emitRand, 0x48);
OFF(PEPackage, emitStep, 0x4C);
OFF(PEPackage, alpha, 0x50);
OFF(PEPackage, alphaRand, 0x54);
OFF(PEPackage, life, 0x58);
OFF(PEPackage, lifeRand, 0x5C);
OFF(PEPackage, pad60, 0x60);
OFF(PEPackage, col, 0x70);
OFF(PEPackage, u, 0x80);
OFF(PEPackage, v, 0x84);
OFF(PEPackage, spinX, 0x88);
OFF(PEPackage, pad8A, 0x8A);
OFF(PEPackage, spinXRand, 0x8C);
OFF(PEPackage, wind, 0x90);
OFF(PEPackage, floorOn, 0x94);
OFF(PEPackage, floorDepth, 0x98);
OFF(PEPackage, pad9C, 0x9C);
SIZE(PEPackage, 0xA0); /* comment */

/* PEPartRec: runtime, ico2/sugipon/include/particleEffect.h:61 */
#if ICO_LAYOUT_EE
OFF(PEPartRec, alive, 0x0);
OFF(PEPartRec, spin, 0x4);
OFF(PEPartRec, pad08, 0x8);
OFF(PEPartRec, pos, 0x10);
OFF(PEPartRec, vel, 0x20);
OFF(PEPartRec, spinX, 0x30);
OFF(PEPartRec, spinY, 0x32);
OFF(PEPartRec, size, 0x34);
OFF(PEPartRec, sizeStep, 0x38);
OFF(PEPartRec, alpha, 0x3C);
OFF(PEPartRec, alphaStep, 0x40);
OFF(PEPartRec, life, 0x44);
OFF(PEPartRec, pad48, 0x48);
OFF(PEPartRec, col, 0x50);
OFF(PEPartRec, u, 0x60);
OFF(PEPartRec, v, 0x64);
OFF(PEPartRec, pad68, 0x68);
SIZE(PEPartRec, 0x70); /* comment */
#endif

/* PEGeo: runtime, ico2/sugipon/include/particleEffect.h:88 */
#if ICO_LAYOUT_EE
OFF(PEGeo, pos, 0x0);
OFF(PEGeo, quat, 0x10);
OFF(PEGeo, pkg, 0x20);
OFF(PEGeo, parts, 0x24);
OFF(PEGeo, prim, 0x28);
OFF(PEGeo, emitted, 0x2C);
OFF(PEGeo, n, 0x30);
OFF(PEGeo, clip, 0x34);
OFF(PEGeo, floorOn, 0x38);
OFF(PEGeo, floor, 0x3C);
OFF(PEGeo, rate, 0x40);
OFF(PEGeo, pad44, 0x44);
OFF(PEGeo, goal, 0x50);
OFF(PEGeo, speed, 0x60);
OFF(PEGeo, proc, 0x64);
OFF(PEGeo, endFunc, 0x68);
OFF(PEGeo, id, 0x6C);
OFF(PEGeo, user, 0x70);
OFF(PEGeo, pad74, 0x74);
SIZE(PEGeo, 0x80); /* comment */
#endif

/* ParticleEffectFile: overlay, ico2/sugipon/include/particleEffect.h:118 */
OFF(ParticleEffectFile, name, 0x0);
OFF(ParticleEffectFile, path, 0x20);
SIZE(ParticleEffectFile, 0x50); /* comment */

/* PoolMesh: runtime, ico2/sugipon/include/pool.h:21 */
#if ICO_LAYOUT_EE
OFF(PoolMesh, nrow, 0x0);
OFF(PoolMesh, ncol, 0x4);
OFF(PoolMesh, sizeX, 0x8);
OFF(PoolMesh, sizeZ, 0xC);
OFF(PoolMesh, mesh, 0x10);
OFF(PoolMesh, height, 0x14);
OFF(PoolMesh, row, 0x18);
OFF(PoolMesh, color, 0x1C);
#endif

/* SpiderKindRec: overlay, ico2/sugipon/include/spider.h:20 */
OFF(SpiderKindRec, jump, 0x0);
OFF(SpiderKindRec, layout, 0xC);
OFF(SpiderKindRec, count, 0x10);
OFF(SpiderKindRec, targetGirl, 0x14);
OFF(SpiderKindRec, upZ, 0x18);
OFF(SpiderKindRec, attack, 0x1C);
SIZE(SpiderKindRec, 0x20); /* comment */

/* StormTestWork: runtime, ico2/sugipon/include/stormTest.h:20 */
#if ICO_LAYOUT_EE
OFF(StormTestWork, num, 0x0);
OFF(StormTestWork, pad04, 0x4);
OFF(StormTestWork, color, 0x10);
OFF(StormTestWork, pkg, 0x20);
OFF(StormTestWork, pad24, 0x24);
SIZE(StormTestWork, 0x30); /* comment */
#endif

/* StreamMotionFile: overlay, ico2/sugipon/include/streamMotionManager.h:13 */
OFF(StreamMotionFile, path, 0x0);
SIZE(StreamMotionFile, 0x30); /* comment */

/* LeverGeoWork: runtime, ico2/sugipon/include/switch.h:19 */
#if ICO_LAYOUT_EE
OFF(LeverGeoWork, shake, 0x0);
OFF(LeverGeoWork, angle, 0x2);
OFF(LeverGeoWork, state, 0x4);
OFF(LeverGeoWork, timer, 0x8);
OFF(LeverGeoWork, base, 0xC);
OFF(LeverGeoWork, handle, 0x10);
OFF(LeverGeoWork, linked, 0x14);
OFF(LeverGeoWork, linkWait, 0x18);
OFF(LeverGeoWork, trigger, 0x1C);
#endif

/* WaterDot: runtime, ico2/sugipon/include/waterDot.h:13 */
#if ICO_LAYOUT_EE
OFF(WaterDot, used, 0x0);
OFF(WaterDot, frame, 0x4);
OFF(WaterDot, life, 0x8);
OFF(WaterDot, scale, 0xC);
OFF(WaterDot, pos, 0x10);
OFF(WaterDot, vel, 0x20);
#endif

/* WeaponDef: overlay, ico2/sugipon/include/weapon.h:19 */
OFF(WeaponDef, length, 0x0);
OFF(WeaponDef, grip, 0x4);
OFF(WeaponDef, power, 0x8);
OFF(WeaponDef, weight, 0xC);
OFF(WeaponDef, word10, 0x10);
OFF(WeaponDef, blur, 0x14);
OFF(WeaponDef, color, 0x18);
OFF(WeaponDef, motOrient, 0x1C);
OFF(WeaponDef, flags, 0x20);
SIZE(WeaponDef, 0x24); /* comment */

/* FumbleRow: overlay, ico2/sugipon/include/weapon.h:34 */
OFF(FumbleRow, pos, 0x0);
OFF(FumbleRow, rotY, 0xC);
OFF(FumbleRow, rotX, 0x10);
OFF(FumbleRow, rotZ, 0x14);
SIZE(FumbleRow, 0x18); /* comment */

/* HandModeCmd: runtime, ico2/fumi/include/enemy_act.h:37 */
#if ICO_LAYOUT_EE
SIZE(HandModeCmd, 0x8); /* config */
#endif

/* GamesysObjInfo: save, ico2/common/include/backStage.h:23 */
SIZE(GamesysObjInfo, 0x40); /* config */

int main(void)
{
    return 0;
}
