#!/usr/bin/env python3
"""embed_shaders.py: turn compiled shader blobs into shaders_gen.c/.h.

Called by cmake/IcoShaders.cmake with a manifest, one shader per line:
    name|stage|entry|spirv-file|dxil-file
the output directory and a version string. Writes shaders_gen.h (the table's
declaration) and shaders_gen.c (the byte arrays and the table). Also checks
the blobs: SPIR-V must start with its magic number, DXIL must be a DXBC
container whose hash is not zero (an unsigned container has a zero hash:
D3D12 would refuse it without experimental shader models).
"""
import struct
import sys

STAGES = {"vertex": 0, "fragment": 1}

HEADER = """/* shaders_gen.h: generated by port/shaders/embed_shaders.py from the HLSL in
 * port/shaders/ (@VERSION@); do not edit. */
#ifndef ICO_SHADERS_GEN_H
#define ICO_SHADERS_GEN_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* stage values equal RhiShaderStage (port/rhi/rhi.h) */
#define ICO_SHADER_STAGE_VERTEX 0
#define ICO_SHADER_STAGE_FRAGMENT 1

typedef struct IcoShaderBlob {
    const char *name; /* lookup key, "<file>_<stage>" */
    int stage;        /* ICO_SHADER_STAGE_* */
    const uint8_t *spirv;
    size_t spirv_len;
    const uint8_t *dxil; /* signed DXIL in a DXBC container */
    size_t dxil_len;
    const char *entry; /* entry point inside the SPIR-V (RhiShaderDesc.entryPoint) */
} IcoShaderBlob;

extern const IcoShaderBlob g_icoShaders[];
extern const unsigned g_icoShaderCount;

/* NULL when no shader has that name. */
const IcoShaderBlob *ico_FindShader(const char *name);

#ifdef __cplusplus
}
#endif

#endif
"""


def check(name, spv, dxil):
    if len(spv) < 20 or len(spv) % 4 or struct.unpack("<I", spv[:4])[0] != 0x07230203:
        sys.exit(f"embed_shaders: {name}: SPIR-V is not a SPIR-V module")
    if len(dxil) < 24 or dxil[:4] != b"DXBC":
        sys.exit(f"embed_shaders: {name}: DXIL is not a DXBC container")
    if dxil[4:20] == bytes(16):
        sys.exit(f"embed_shaders: {name}: DXIL is unsigned (is libdxil.so beside dxc?)")


def array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    manifest, outdir, version = sys.argv[1], sys.argv[2], sys.argv[3]
    rows = []
    for line in open(manifest, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        name, stage, entry, spv_path, dxil_path = line.split("|")
        spv = open(spv_path, "rb").read()
        dxil = open(dxil_path, "rb").read()
        check(name, spv, dxil)
        rows.append((name, STAGES[stage], entry, spv, dxil))
    rows.sort(key=lambda r: r[0])
    names = [r[0] for r in rows]
    if len(set(names)) != len(names):
        sys.exit("embed_shaders: duplicate shader name")

    out = [f"/* shaders_gen.c: generated by port/shaders/embed_shaders.py ({version}); do not edit. */",
           '#include "shaders_gen.h"', "#include <string.h>", ""]
    for i, (_, _, _, spv, dxil) in enumerate(rows):
        out.append(array(f"spv_{i}", spv))
        out.append(array(f"dxil_{i}", dxil))
        out.append("")
    out.append("const IcoShaderBlob g_icoShaders[] = {")
    for i, (name, stage, entry, _, _) in enumerate(rows):
        out.append(f'    {{"{name}", {stage}, spv_{i}, sizeof(spv_{i}), '
                   f'dxil_{i}, sizeof(dxil_{i}), "{entry}"}},')
    out += [
        "};",
        f"const unsigned g_icoShaderCount = {len(rows)};",
        "",
        "const IcoShaderBlob *ico_FindShader(const char *name)",
        "{",
        "    for (unsigned i = 0; i < g_icoShaderCount; i++) {",
        "        if (strcmp(g_icoShaders[i].name, name) == 0) {",
        "            return &g_icoShaders[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
    ]
    with open(f"{outdir}/shaders_gen.h", "w", encoding="utf-8") as f:
        f.write(HEADER.replace("@VERSION@", version))
    with open(f"{outdir}/shaders_gen.c", "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


main()
